[package]
name = "inst-macros"
version = "0.1.0"
description = "The Inst Macros Proc Macros Crate (only use via `inst` crate)"
readme = "README.md"
keywords = ["rust", "inst", "instance", "proc-macro",]
documentation = "https://auguth.github.io/rust-suite/rust-doc/inst_macros/index.html"

license.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true


[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-suite.workspace = true
prettyplease.workspace = true
proc-macro2.workspace = true
const_format.workspace = true
paste.workspace = true

[features]
default = []
dev = ["proc-suite/dev"]