// SPDX-License-Identifier: MPL-2.0
//
// Part of Auguth Labs open-source softwares.
// Built for the Rust Programming Language Ecosystem.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2026 Auguth Labs (OPC) Pvt Ltd, India

// ===============================================================================
// `````````````````````````````````` TRAIT INST `````````````````````````````````
// ===============================================================================

//! Provides the transformation pipeline for instance trait definitions.
//!
//! The module transforms an `#[inst(...)]` trait into its internal expanded
//! representation, including generated instance-counter const generics,
//! instance-node associated types, and instance sum types.
//!
//! The transformation is performed in separate phases for the trait generic
//! header, instance-node associated types, which are unified by
//! [`TraitInst`]. A documentation-only `cfg(not(feature = "inst"))` representation 
//! is also generated by [`TraitInstDoc`] so the public instance-trait interface can
//! be documented without exposing its internal generated generics.
//!
//! The module also provides the bound and generic-argument helpers used to
//! resolve instance-trait bounds and inject placeholder instance arguments
//! during node transformation.
//!
//! Support-crate delegation is used to invoke the explicit instance-trait and
//! instance-node macro phases after the initial transformations.

// ===============================================================================
// ``````````````````````````````````` IMPORTS ```````````````````````````````````
// ===============================================================================

// --- Proc Macro Crates ---
use proc_macro2::{Span, TokenStream};
use quote::{ToTokens,};
use syn::{
    AngleBracketedGenericArguments, ConstParam, File, GenericArgument, GenericParam, Ident, Item, ItemTrait, LitInt, PathArguments, TraitItem, TypeParamBound, parse_quote, punctuated::Punctuated, token::{PathSep, Plus},
};

// --- Local Crate ---
use crate::{
    Extraction, Inst, Transformation, args::{BoundInstance, InstModelLength, 
        InstanceModel, NodeArgs}, 
        errors::{ParseBug, ProcParseErr, TraitBug, TraitError}, 
};

// --- Proc Suite ---
use proc_suite::{DocAttr, IdentList, InsertDocs, IntList, SupportCrate, misc::*};

// ===============================================================================
// ```````````````````````````` TRAIT INST ENTRY-POINT ```````````````````````````
// ===============================================================================

/// Transforms an instance trait through the [`crate::inst`] macro pipeline.
///
/// An instance trait declares named instance parameters, which are lowered
/// into const generic instance counters. Instance-node associated types,
/// instance sum types are also transformed into their 
/// generated representations.
///
/// Before transformation:
///
/// ```ignore
/// #[inst(Module, Function)]
/// trait Hasher {
///     #[node(..)]
///     type Hash;
///
///     #[sum]
///     type Output;
/// }
/// ```
///
/// The source trait is transformed into an internal `cfg(not(feature = "int"))` form.
/// The [`SupportCrate`] provides the public crate path, which re-exports the
/// explicit macro entry points from the `instances-macro` crate. Generated
/// attributes therefore reference those macros through the support crate:
///
/// ```ignore
/// #[cfg(not(feature = "inst"))]
/// #[support_crate::instance_trait_explicit_target(0, 1)]
/// #[support_crate::instance_node_explicit_target]
/// trait Hasher<const __INST_0: u8, const __INST_1: u8> {
///     #[instance_sub(...)]
///     type Hash;
/// 
///     type Output;
/// }
/// ```
///
/// The transformation of the trait header generics and the transformation
/// of `#[node(...)]` associated types are separate transformation phases.
/// 
/// They are independently applied and validated, but are unified as part of
/// the same [`TraitInst`] macro pipeline.
///
/// A separate `cfg(not(feature = "inst"))` copy is retained for rustdoc 
/// and contains the generated documentation for the instance trait, 
/// its instance nodes, and its instance sum types:
///
/// ```ignore
/// #[cfg(not(feature = "inst"))]
/// /// Documentation Disclaimer for Instance Traits
/// trait Hasher {
///     /// Documentation Disclaimer for Instance Nodes
///     type Hash;
/// }
/// ```
///
/// The documentation representation intentionally hides the generated
/// instance-counter generics. The public trait interface is documented in
/// terms of the instance macros provided by this crate; the generated
/// implementation form is an internal expansion detail.
///
/// Thus, the expanded implementation is used when `inst` is enabled,
/// while the documentation-oriented copy is used when `inst` is not enabled.
/// The transformation also adds the metadata required for delegated macro
/// expansion.
#[derive(Debug, Clone)]
pub struct TraitInst;

impl Transformation<File, TokenStream> for TraitInst {
    fn raw_transform(
        &self,
        transform: &mut File,
        context: &TokenStream,
    ) -> Result<(), proc_macro2::TokenStream> {
        if transform.items.len() > 1 {
            return Err(ParseBug::TooManyItemsToTransform {}.into());
        }
        let Some(Item::Trait(trait_)) = transform
            .items
            .iter_mut()
            .find(|item| matches!(item, Item::Trait(_)))
        else {
            return Err(TraitBug::FileContainsNoTrait {}.into());
        };
        let idents = match context.is_empty() {
            true => None,
            false => {
                let idents = IdentList::checked_extract(context, &())?;
                Some(idents)
            }
        };

        let mut doc_trait = trait_.clone();
        let mut addon = File {shebang: None, attrs: Vec::new(), items: Vec::new()};

        ItemTypeInst::checked_transform(&ItemTypeInst, &mut (&mut addon, trait_), &idents)?;
        if let Some(idents) = &idents {
            TraitGenericsInst::checked_transform(&TraitGenericsInst, trait_, idents)?;
        }
        cfg_feature_disclaimer(&mut trait_.attrs);
        trait_.attrs.insert(0, Inst::feature());

        for item in addon.items {
            transform.items.push(item);
        }

        TraitInstDoc::checked_transform(&TraitInstDoc, &mut doc_trait, &idents)?;
        doc_trait.attrs.insert(0, Inst::not_feature());
        transform.items.push(Item::Trait(doc_trait));

        Ok(())
    }

    fn validate_transform(
        &self,
        transform: &File,
        context: Option<&TokenStream>,
    ) -> Result<(), proc_macro2::TokenStream> {
        let find = |doc: bool, item: &Item| -> bool {
            let Item::Trait(trait_) = item else {
                return false;
            };
            trait_.attrs.iter().any(|attr| {
                if *attr == Inst::feature() {
                    if doc {false} else {true}
                } else if *attr == Inst::not_feature() {
                    if doc {true} else {false}

                } else {
                    false
                }
            }) 
        };
        let Some(doc_trait) = transform.items.iter().find(|item| find(true, item)) else {
            return Err(TraitBug::TransformedFileDoesNotHaveDocTarget {}.into());
        };
        let Some(not_doc_trait) = transform.items.iter().find(|item| find(false, item)) else {
            return Err(TraitBug::TransformedFileDoesNotHaveNotDocTarget {}.into());
        };

        let Item::Trait(trait_) = not_doc_trait else {
            unreachable!()
        };
        if !trait_.clone().has_docs() {
            return Err(TraitBug::NotDocTargetDoesNotHaveDocs {}.into());
        }

        if let Some(context) = context {
            if !context.is_empty() {
                let Item::Trait(trait_) = doc_trait else {
                    unreachable!()
                };
                if !trait_.clone().has_docs() {
                    return Err(TraitBug::DocTargetDoesNotHaveDocs {}.into());
                }
            }
        }

        Ok(())
    }
}

// ===============================================================================
// ```````````````````````````` TRAIT INST DOC-TARGET ````````````````````````````
// ===============================================================================

/// Transforms an instance trait into its documentation representation.
///
/// This transformation is applied to the `cfg(not(feature = "inst"))` copy produced by
/// [`TraitInst`]. It removes the internal `#[node(...)]`, `#[sum]` 
/// attributes and replaces them with generated rustdoc describing the
/// instance nodes and instance sum types.
///
/// For an instance trait, it also adds a trait-level description containing
/// its declared instance parameters and points users to the [`crate::inst`]
/// macros used to define and access instance traits.
///
/// Before transformation:
///
/// ```ignore
/// #[inst(Module, Function)]
/// trait Hasher {
///     #[node(Node(..))]
///     type Hash: Node;
///
///     #[sum]
///     type Output;
/// }
/// ```
///
/// The documentation representation retains the user-facing trait while
/// replacing the instance-specific attributes with documentation:
///
/// ```ignore
/// /// # Instance Trait `(Module, Function)`
/// ///
/// /// An instance trait such as `Hasher` is implemented using
/// /// `#[inst(..)]` and its trait items are accessed through
/// /// `inst_get!()` or `inst_direct!()`.
/// trait Hasher {
///     /// # Instance Node [`Node`]
///     ///
///     /// An instance node associated accessed through `inst_get!()`.
///     type Hash;
///     
///     /// # Instance Sum Type [`Hasher`]
///     ///
///     /// An instance sum type is interoperable across dynamic instances.
///     type Output;
/// }
/// ```
///
/// When no instance parameters are supplied, the transformation does not
/// permit `#[sum]` associated types, since instance sum types are only valid
/// for instance traits.
#[derive(Debug, Clone)]
pub struct TraitInstDoc;

impl Transformation<ItemTrait, Option<IdentList>> for TraitInstDoc {
    fn raw_transform(
        &self,
        transform: &mut ItemTrait,
        context: &Option<IdentList>,
    ) -> Result<(), proc_macro2::TokenStream> {
        let ident = transform.ident.clone();

        if let Some(idents) = context {
            transform.attrs.prepend_docs(vec![
                DocAttr::Heading {
                    level: 0,
                    content: vec![DocAttr::Raw(format!(
                        "Instance Trait `({})`",
                        idents.to_token_stream()
                    ))],
                },
                DocAttr::Raw(format!(
                    "An instance trait such as `{}` is implemented using ",
                    ident,
                )),
                DocAttr::Link {
                    title: "#[inst(..)]".to_string(),
                    url: "inst::inst".to_string(),
                },
                DocAttr::Raw(" and its trait items are accessed through ".to_string()),
                DocAttr::Link {
                    title: "inst_get!()".to_string(),
                    url: "inst::inst_get".to_string(),
                },
                DocAttr::Raw(" *or* ".to_string()),
                DocAttr::Link {
                    title: "inst_direct!()".to_string(),
                    url: "inst::inst_direct".to_string(),
                },
                DocAttr::Raw(".".to_string()),
                DocAttr::LineBreak,
                DocAttr::Raw("*See* ".to_string()),
                DocAttr::Link {
                    title: "`inst::trait`".to_string(),
                    url: "inst::trait".to_string(),
                },
                DocAttr::Raw(" *for instance trait definitions,* ".to_string()),
                DocAttr::Link {
                    title: "`inst::impl`".to_string(),
                    url: "inst::impl".to_string(),
                },
                DocAttr::Raw(" *for instance implementations.*".to_string()),
                DocAttr::LineBreak,
            ]);
        }

        for item in &mut transform.items {
            let TraitItem::Type(ty) = item else {
                continue;
            };

            let mut docs = Vec::new();
            let mut node = None;
            let mut is_sum = false;

            let attrs = std::mem::take(&mut ty.attrs);
            let mut retained_attrs = Vec::with_capacity(attrs.len());

            let node_ident = Inst::node();
            let sum_ident = Inst::sum();

            for attr in attrs {
                let path_ident = attr.path().get_ident();

                match path_ident {
                    Some(ident) if *ident == node_ident => {
                        let tokens = match &attr.meta {
                            syn::Meta::List(meta_list) => &meta_list.tokens,
                            syn::Meta::Path(_) => {
                                return Err(TraitBug::NodeRequiresArgs {}.into());
                            }
                            syn::Meta::NameValue(_) => {
                                return Err(TraitBug::NodeRequiresArgsNotValue {}.into());
                            }
                        };

                        if tokens.is_empty() {
                            return Err(TraitBug::NodeRequiresArgs {}.into());
                        }

                        node = Some(BoundInstance::checked_extract(tokens, &())?);
                    }
                    Some(ident) if *ident == sum_ident => {
                        if context.is_none() {
                            return Err(TraitError::SumNotAllowed { attr }.into());
                        }

                        if !matches!(&attr.meta, syn::Meta::Path(_)) {
                            return Err(TraitError::SumNoArgs { attr }.into());
                        }

                        is_sum = true;
                    }

                    _ => retained_attrs.push(attr),
                } 
            }

            ty.attrs = retained_attrs;

            if let Some(bound) = node {
                let path = bound.path.to_token_stream().to_string();

                docs.extend([
                    DocAttr::Heading {
                        level: 1,
                        content: vec![
                            DocAttr::Raw("Instance Node ".to_string()),
                            DocAttr::Ref(path),
                            DocAttr::Raw(format!("`{}`", bound.bound.to_token_stream())),
                        ],
                    },
                    DocAttr::Raw("An instance node associated accessed through ".to_string()),
                    DocAttr::Link {
                        title: "inst_get!()".to_string(),
                        url: "inst::inst_get".to_string(),
                    },
                    DocAttr::Raw(".".to_string()),
                    DocAttr::LineBreak,
                    DocAttr::Raw("*See* ".to_string()),
                    DocAttr::Link {
                        title: "`inst::node`".to_string(),
                        url: "inst::node".to_string(),
                    },
                    DocAttr::Raw(" *for instance node definitions and syntax.*".to_string()),
                    DocAttr::LineBreak,
                ]);
            }

            if is_sum {
                docs.extend([
                    DocAttr::Heading {
                        level: 1,
                        content: vec![
                            DocAttr::Raw("Instance Sum Type ".to_string()),
                            DocAttr::Ref(ident.to_string()),
                        ],
                    },
                    DocAttr::Raw(
                        "An instance sum type is interoperable across \
                         dynamic instances."
                            .to_string(),
                    ),
                    DocAttr::LineBreak,
                    DocAttr::Raw("*See* ".to_string()),
                    DocAttr::Link {
                        title: "`inst::sum`".to_string(),
                        url: "inst::sum".to_string(),
                    },
                    DocAttr::Raw(" *for instance sum type definitions.*".to_string()),
                    DocAttr::LineBreak,
                ]);
            }

            ty.attrs.prepend_docs(docs);
        }

        Ok(())
    }

    fn validate_transform(
        &self,
        transform: &ItemTrait,
        context: Option<&Option<IdentList>>,
    ) -> Result<(), proc_macro2::TokenStream> {
        if let Some(Some(_)) = context {
            if !&transform.attrs.clone().has_docs() {
                return Err(TraitBug::TraitDocsNotFound {}.into());
            }
        }

        for item in &transform.items {
            let TraitItem::Type(ty) = item else {
                continue;
            };
            if ty.attrs.iter().any(|attr| attr.path().is_ident(&Inst::sum())) {
                return Err(TraitBug::DocTargetInstTraitSumAttrExists {}.into());
            }
            if ty.attrs.iter().any(|attr| attr.path().is_ident(&Inst::node())) {
                return Err(TraitBug::DocTargetInstTraitNodeAttrExists {}.into());
            }
        }
        Ok(())
    }
}

// ===============================================================================
// `````````````````````````` INST TRAIT GENERICS HEADER `````````````````````````
// ===============================================================================

/// Transforms the generic header of an instance trait.
///
/// For every declared instance parameter, this phase inserts a generated
/// `u8` const generic used as the instance counter. The generated counters
/// are inserted after all lifetime parameters and their generic position indexes are
/// recorded in `instance_trait_explicit_target` delegated attribute arguments.
///
/// This phase is independent of the transformation of instance-node
/// associated types. Both transformations are executed as part of the same
/// [`TraitInst`] pipeline.
///
/// Before transformation:
///
/// ```ignore
/// #[inst(Module, Function)]
/// trait Hasher<'a, T> {
///     // ...
/// }
/// ```
///
/// After transformation:
///
/// ```ignore
/// #[instance_trait_explicit_target(2, 3)]
/// trait Hasher<'a, T, const __INST_0: u8, const __INST_1: u8> {
///     // ...
/// }
/// ```
///
/// The indexes `2` and `3` identify the positions of the generated instance
/// counters in the trait's generic parameter list. Existing lifetime
/// parameters remain at the front, while the generated instance counters are
/// inserted before other non-lifetime parameters when applicable.
///
/// The `instance_trait_explicit_target` attribute records the generic indexes,
/// while [`SupportCrate::delegate_attribute`] appends the delegate macro for
/// the final transformation by [`crate::delegate_support_crate_internal_only`].
#[derive(Debug, Clone)]
struct TraitGenericsInst;

impl Transformation<ItemTrait, IdentList> for TraitGenericsInst {
    fn raw_transform(
        &self,
        transform: &mut ItemTrait,
        context: &IdentList,
    ) -> Result<(), proc_macro2::TokenStream> {
        if context.idents.len() > 4 {
            return Err(TraitError::Max4Params {
                idents: context.clone(),
            }
            .into());
        }
        // generic params (for each instance counter)
        let mut collect = Vec::new();
        for (i, _) in context.idents.iter().enumerate() {
            let id_str = i.to_string();
            let id = id_str.as_bytes();
            let ident = gen_const_ident_with_suffix::<TraitInst>(Some(id));
            collect.push(GenericParam::Const(ConstParam {
                attrs: Default::default(),
                const_token: Default::default(),
                ident,
                colon_token: Default::default(),
                ty: parse_quote!(u8),
                eq_token: Default::default(),
                default: Default::default(),
            }));
        }

        let params = &mut transform.generics.params;

        // only append params after lifetimes
        let mut seen_non_lifetime = false;
        for param in params.iter() {
            if let GenericParam::Lifetime(lt) = param {
                if seen_non_lifetime {
                    return Err(ProcParseErr::LifetimeShouldBeDeclaredFront {
                        lt: lt.lifetime.clone(),
                    }
                    .into());
                }
            } else {
                seen_non_lifetime = true;
            }
        }

        let index = params
            .iter()
            .position(|param| !matches!(param, GenericParam::Lifetime(_)))
            .unwrap_or(params.len());

        let mut indexes = Vec::new();
        for (offset, param) in collect.into_iter().enumerate() {
            let offsetted = index + offset;
            params.insert(offsetted, param);
            indexes.push(LitInt::new(&offsetted.to_string(), Span::call_site()));
        }

        let attrs = &mut transform.attrs;

        let support_crate = Inst::support_crate();
        let trait_target = Inst::trait_target();
        attrs.insert(
            0,
            parse_quote!(#[#support_crate::#trait_target(#(#indexes),*)]),
        );
        Inst::delegate_attribute(attrs);

        for item in &mut transform.items {
            let TraitItem::Type(ty) = item else {
                continue;
            };
            if ty.attrs.iter().any(|attr| attr.path().is_ident(&Inst::sum())) {
                cfg_feature_disclaimer(ty);
            }
        }

        Ok(())
    }

    fn validate_transform(
        &self,
        transform: &ItemTrait,
        context: Option<&IdentList>,
    ) -> Result<(), proc_macro2::TokenStream> {
        let support_crate = Inst::support_crate();
        let Some(delegate_macro) = Inst::delegate_macro() else {
            return Err(TraitBug::DelegateMacroNotInitialized {}.into());
        };

        let Some((idx, inst_attr)) = transform.attrs.iter().enumerate().find_map(|(i, attr)| {
            let trait_target = Inst::trait_target();
            if *attr.path() == parse_quote!(#support_crate::#trait_target) {
                return Some((i, attr));
            }
            return None;
        }) else {
            return Err(TraitBug::InstanceTraitMacroNotFound {}.into());
        };

        if !transform.attrs.iter().enumerate().any(|(i, attr)| {
            if i <= idx {
                return false;
            }
            *attr.path() == parse_quote!(#support_crate::#delegate_macro)
        }) {
            return Err(TraitBug::DelegateMacroNotFound {}.into());
        }

        let tokens = match &inst_attr.meta {
            syn::Meta::List(meta_list) => &meta_list.tokens,
            _ => return Err(TraitBug::InstanceTraitMacroArgsNotFound {}.into()),
        };

        let Ok(indexes) = IntList::checked_extract(tokens, &()) else {
            return Err(TraitBug::InstanceTraitMacroIndexesParseFailed {}.into());
        };

        let Some(context) = context else {
            return Ok(());
        };

        let params = &transform.generics.params;
        let mut seen_non_lifetime = false;
        for param in params.iter() {
            if matches!(param, GenericParam::Lifetime(_)) {
                if seen_non_lifetime {
                    return Err(ParseBug::LifetimeShouldBeDeclaredFront {}.into());
                }
            } else {
                seen_non_lifetime = true;
            }
        }
        let mut index = params
            .iter()
            .position(|param| !matches!(param, GenericParam::Lifetime(_)))
            .unwrap_or(params.len());

        let mut collect = Vec::new();
        for (i, _) in context.idents.iter().enumerate() {
            let id_str = i.to_string();
            let id = id_str.as_bytes();
            let ident = gen_const_ident_with_suffix::<TraitInst>(Some(id));
            collect.push((index.clone(), ident));
            index = index + 1;
        }

        if collect.len() != indexes.ints.len() {
            return Err(TraitBug::InstanceTraitMacroIndexesInconsistent {}.into());
        }

        for ((index, ident), int) in collect.into_iter().zip(indexes.ints) {
            if index != parse_pos_usize(&int)? {
                return Err(TraitBug::InstanceCounterIndexInvalid {}.into());
            }

            let Some(param) = params.get(index) else {
                return Err(TraitBug::InstanceCounterConstNotFound {}.into());
            };

            let GenericParam::Const(c) = param else {
                return Err(TraitBug::InstanceCounterGenericNotConst {}.into());
            };

            if c.ident != ident {
                return Err(TraitBug::InstanceCounterGenericInvalidIdent {}.into());
            }

            if c.ty != parse_quote!(u8) {
                return Err(TraitBug::InstanceCounterGenericInvalidType {}.into());
            }
        }

        Ok(())
    }
}

// ===============================================================================
// `````````````````````````` INST TRAIT ASSOCIATE TYPES `````````````````````````
// ===============================================================================

/// Transforms instance type associated items declared on an instance trait.
///
/// The transformation validates the instance-specific associated types
/// declared on the trait and dispatches their transformation to the
/// corresponding instance type transformation.
///
/// An associated type may contain `#[node(...)]`. Instance node are only valid on
/// associated type items; using either attribute on an associated constant or
/// function produces an error.
///
/// The transformation also validates references to the containing trait from
/// instance type declarations when invoked in the nested transformation
/// context. Such references are rejected to prevent an instance trait from
/// recursively referring to itself through its generated instance types.
///
/// At least one instance type declaration is required when transforming an
/// instance trait directly. When invoked from a nested transformation, the
/// absence of an instance type declaration is allowed.
///
/// After validation, the transformation delegates the actual generation to:
///
/// - [`ItemTypeNodeInst`] for `#[node(...)]` associated types, including their
///   generated instance node representations and access implementations
///
/// This transformation therefore acts as the entry point for instance
/// associated type processing, while the node transformations own
/// the generation of their respective representations and access machinery.
#[derive(Debug, Clone)]
struct ItemTypeInst;

type AddonSpace<'a> = (&'a mut File, &'a mut ItemTrait);

impl<'a> Transformation<AddonSpace<'a>, Option<IdentList>> for ItemTypeInst {
    fn raw_transform(&self, transform: &mut AddonSpace<'a>, context: &Option<IdentList>) -> Result<(), proc_macro2::TokenStream> {
        let trait_ = &mut transform.1;

        let node = Inst::node();
        let mut found = false;

        for item in &trait_.items {
            match item {
                TraitItem::Const(c) => {
                    if let Some(attr) = c.attrs.iter().find(|attr| attr.path().is_ident(&node))
                    {
                        return Err(
                            TraitError::NodeOnlyInTypeAssoc { attr: attr.clone() }.into()
                        );
                    }
                }
                TraitItem::Fn(f) => {
                    if let Some(attr) = f.attrs.iter().find(|attr| attr.path().is_ident(&node))
                    {
                        return Err(
                            TraitError::NodeOnlyInTypeAssoc { attr: attr.clone() }.into()
                        );
                    }
                }
                TraitItem::Type(t) => {
                    let node = t.attrs.iter().find(|attr| attr.path().is_ident(&Inst::node()));

                    if node.is_some() {
                        found = true;
                    }
                }
                _ => {}
            }
        }
        if !found && context.is_none() {
            return Ok(())
        }

        ItemTypeNodeInst::checked_transform(&ItemTypeNodeInst, &mut transform.1, &())?;
        Ok(())
    }

    fn validate_transform(&self, transform: &AddonSpace<'a>, _: Option<&Option<IdentList>>) -> Result<(), proc_macro2::TokenStream> {
        ItemTypeNodeInst::validate_transform(&ItemTypeNodeInst, &transform.1, None)?;
        Ok(())
    }
}

// ===============================================================================
// ````````````````````````````` INST ASSOC TYPE NODE ````````````````````````````
// ===============================================================================

/// Transforms instance-node associated types declared on an instance trait.
///
/// Each `#[node(...)]` attribute is parsed as a [`BoundInstance`], its
/// instance-trait bound is resolved, and the instance model is lowered into
/// [`NodeArgs`]. The resulting node arguments are attached as an internal
/// `#[instance_sub(...)]` attribute annotation consumed by delegated attribute macro
/// `instance_node_explicit_target`.
///
/// `#[node(...)]` is only valid on associated types; constants and functions
/// cannot declare instance nodes.
///
/// The `instance_node_explicit_target` attribute is then added to the trait,
/// and [`SupportCrate::delegate_attribute`] appends the delegate macro for
/// the final transformation by [`crate::delegate_support_crate_internal_only`].
///
/// Before transformation:
///
/// ```ignore
/// #[node(Crypto::Hasher(Module, Function))]
/// type Hash;
/// ```
///
/// After this phase:
///
/// ```ignore
/// #[instance_sub(...)]
/// type Hash;
///
/// // and on the trait
///
/// #[support_crate::instance_node_explicit_target]
/// #[support_crate::delegate_support_crate_internal_only]
/// trait Hasher { ... }
/// ```
///
/// The transformation of the node arguments is performed separately from the
/// trait generic-header transformation, but both phases are unified by the
/// [`TraitInst`] pipeline.
#[derive(Debug, Clone)]
struct ItemTypeNodeInst;

impl Transformation<ItemTrait> for ItemTypeNodeInst {
    fn raw_transform(
        &self,
        transform: &mut ItemTrait,
        _: &(),
    ) -> Result<(), proc_macro2::TokenStream> {
        let node = Inst::node();

        let mut ty_items = Vec::new();
        for item in &mut transform.items {
            if let TraitItem::Type(t) = item {
                if t.attrs.iter().any(|attr| attr.path().is_ident(&node)) {
                    ty_items.push(t);
                }
            }
        }

        for ty in ty_items {
            let mut node_attr = None;
            let mut build = Vec::new();
            for attr in &ty.attrs {
                if !attr.path().is_ident(&node) {
                    build.push(attr.clone());
                    continue;
                }
                if node_attr.is_some() {
                    return Err(TraitError::DoubleNode { attr: attr.clone() }.into());
                };
                node_attr = Some(attr.clone());
            }
            ty.attrs = build;
            let Some(node_attr) = node_attr else {
                return Err(TraitBug::InconsistencyFindingNodeAttribute {}.into());
            };

            let tokens = match &node_attr.meta {
                syn::Meta::List(meta_list) => &meta_list.tokens,
                syn::Meta::Path(_) => {
                    return Err(TraitError::NodeRequiresArgs {
                        attr: node_attr.clone(),
                    }
                    .into());
                }
                syn::Meta::NameValue(meta) => {
                    return Err(TraitError::NodeRequiresArgsNotValue { meta: meta.clone() }.into());
                }
            };
            if tokens.is_empty() {
                return Err(TraitError::NodeRequiresArgs {
                    attr: node_attr.clone(),
                }
                .into());
            }

            let inst = BoundInstance::checked_extract(tokens, &())?;

            let indexes = append_placeholder_args(&mut ty.bounds, &inst.path, &inst.bound, true)?;

            let node_args = NodeArgs::checked_extract(&inst.bound, &indexes)?;

            let attrs = &mut ty.attrs;

            let sub_target = Inst::subscriber();
            attrs.insert(0, parse_quote!(#[#sub_target(#node_args)]));

            cfg_feature_disclaimer(ty);
        }

        let attrs = &mut transform.attrs;
        let support_crate = Inst::support_crate();
        let node_target = Inst::node_target();
        attrs.insert(
            0,
            parse_quote!(#[#support_crate::#node_target]),
        );
        Inst::delegate_attribute(attrs);

        Ok(())
    }

    fn validate_transform(
        &self,
        transform: &ItemTrait,
        _: Option<&()>,
    ) -> Result<(), proc_macro2::TokenStream> {
        let support_crate = Inst::support_crate();
        let Some(delegate_macro) = Inst::delegate_macro() else {
            return Err(TraitBug::DelegateMacroNotInitialized {}.into());
        };

        let Some((idx, inst_attr)) = transform.attrs.iter().enumerate().find_map(|(i, attr)| {
            let node_target = Inst::node_target();
            if *attr.path() == parse_quote!(#support_crate::#node_target) {
                return Some((i, attr));
            }
            return None;
        }) else {
            return Err(TraitBug::InstanceTraitNodeMacroNotFound {}.into());
        };

        if !transform.attrs.iter().enumerate().any(|(i, attr)| {
            if i <= idx {
                return false;
            }
            *attr.path() == parse_quote!(#support_crate::#delegate_macro)
        }) {
            return Err(TraitBug::DelegateMacroNotFound {}.into());
        }

        let syn::Meta::Path(_) = &inst_attr.meta else {
            return Err(TraitBug::InstanceTraitNodeMacroArgsFound {}.into());
        };

        let node = Inst::node();

        for item in &transform.items {
            match item {
                TraitItem::Const(c) => {
                    if c.attrs.iter().any(|attr| attr.path().is_ident(&node)) {
                        return Err(TraitBug::NodeOnlyInTypeAssoc {}.into());
                    }
                }
                TraitItem::Fn(f) => {
                    if f.attrs.iter().any(|attr| attr.path().is_ident(&node)) {
                        return Err(TraitBug::NodeOnlyInTypeAssoc {}.into());
                    }
                }
                TraitItem::Type(ty) => {
                    if !ty
                        .attrs
                        .iter()
                        .any(|attr| attr.path().is_ident(&Inst::subscriber()))
                    {
                        continue;
                    }
                    // rest validation requires re-parsing which is not required
                }
                _ => {}
            }
        }

        Ok(())
    }
}

// ===============================================================================
// `````````````````````````````` HELPER FUNCTIONS ```````````````````````````````
// ===============================================================================

/// A trait-bound is matched against `path`. The matching trait bound is removed,
/// its instance arguments are appended after lifetime arguments, and the
/// transformed bound is inserted at the beginning of the bounds list.
///
/// If `push_args` is `true`, each instance parameter position receives a
/// placeholder const argument (`0`). If `false`, only the positions are
/// calculated and returned.
///
/// Before:
///
/// ```ignore
/// T: Crypto::Hasher + Send
/// ```
///
/// After with `bound = (Module, Function)` and `push_args = true`:
///
/// ```ignore
/// T: Crypto::Hasher<0, 0> + Send
/// ```
///
/// The returned [`IntList`] contains the generic argument positions of the
/// inserted instance counters.
pub fn append_placeholder_args(
    bounds: &mut Punctuated<TypeParamBound, Plus>,
    path: &Punctuated<Ident, PathSep>,
    bound: &InstanceModel,
    push_args: bool,
) -> Result<IntList, TokenStream> {
    let mut found = None;
    let mut build = Punctuated::<TypeParamBound, Plus>::new();

    for t_bound in bounds.iter() {
        let TypeParamBound::Trait(trait_) = t_bound else {
            build.push(t_bound.clone());
            continue;
        };

        let trait_path = trait_.path.segments.iter().map(|seg| &seg.ident).rev();
        let asked = path.iter().rev();

        if asked.len() != trait_path.len() {
            build.push(t_bound.clone());
            continue;
        }

        if asked.zip(trait_path).all(|(given, orig)| given == orig) {
            if found.is_some() {
                return Err(TraitError::DuplicateInstanceTraitBound {
                    bound: trait_.clone(),
                }
                .into());
            }

            found = Some(trait_.clone());
            continue;
        }

        build.push(t_bound.clone());
    }

    *bounds = build;

    let Some(mut trait_bound) = found else {
        return Err(TraitError::ExpectedInstTraitNodeBound {
            bounds: bounds.clone(),
            exp: path.clone(),
        }
        .into());
    };

    let indexes = append_placeholder_args_to_trait(&mut trait_bound.path, bound, push_args)?;

    bounds.insert(0, TypeParamBound::Trait(trait_bound));

    Ok(indexes)
}

/// Appends placeholder instance arguments to an instance-trait path.
///
/// The instance arguments are inserted after all lifetime arguments. One
/// position is produced for each parameter in the [`InstanceModel`].
///
/// With `push_args` enabled, a `0` const argument is inserted at each
/// position; otherwise only the positions are returned.
///
/// ```ignore
/// Crypto::Hasher<'a, T>
/// ```
///
/// with two instance parameters becomes:
///
/// ```ignore
/// Crypto::Hasher<'a, 0, 0, T>
/// ```
///
/// The returned [`IntList`] contains the positions at which the instance
/// arguments were inserted.
pub fn append_placeholder_args_to_trait(
    path: &mut syn::Path,
    bound: &InstanceModel,
    push_args: bool,
) -> Result<IntList, TokenStream> {
    let args = &mut path.segments.last_mut().unwrap().arguments;

    let angle = match args {
        PathArguments::None => {
            *args = PathArguments::AngleBracketed(AngleBracketedGenericArguments {
                colon2_token: Default::default(),
                lt_token: Default::default(),
                args: Default::default(),
                gt_token: Default::default(),
            });

            let PathArguments::AngleBracketed(angle) = args else {
                unreachable!()
            };

            angle
        }

        PathArguments::AngleBracketed(angle) => angle,

        PathArguments::Parenthesized(paren) => {
            return Err(TraitError::ParenthesizedInstTraitNodeBound {
                paren: paren.clone(),
            }
            .into());
        }
    };

    // Only append params after lifetimes.
    let mut seen_non_lifetime = false;

    for param in angle.args.iter() {
        if let GenericArgument::Lifetime(lt) = param {
            if seen_non_lifetime {
                return Err(ProcParseErr::LifetimeShouldBeDeclaredFront { lt: lt.clone() }.into());
            }
        } else {
            seen_non_lifetime = true;
        }
    }

    let index = angle
        .args
        .iter()
        .position(|param| !matches!(param, GenericArgument::Lifetime(_)))
        .unwrap_or(angle.args.len());

    let mut indexes = IntList::default();

    for offset in 0..InstModelLength::checked_extract(bound, &())?.0 {
        let offsetted = index + offset;

        if push_args {
            angle
                .args
                .insert(offsetted, GenericArgument::Const(parse_quote!(0)));
        }

        indexes
            .ints
            .push(LitInt::new(&offsetted.to_string(), Span::call_site()));
    }

    if angle.args.is_empty() {
        *args = PathArguments::None;
    }

    Ok(indexes)
}

/// Prepends a inst cfg feature documentation disclaimer.
pub fn cfg_feature_disclaimer<T: InsertDocs>(item: &mut T) {
    item.prepend_docs(vec![
        DocAttr::Raw(
            "*Note: This is an internal expansion of `cfg(feature = \"inst\")`*"
                .to_string(),
        ),
        DocAttr::Bullet {
            level: 0,
            content: vec![DocAttr::Raw(
                "This may include internal proc-macro expansions which should not be used in user scope as it may be susceptible to change."
                    .to_string(),
            )],
        },
        DocAttr::Bullet {
            level: 0,
            content: vec![DocAttr::Raw(
                "For authoritative documentation, rely on plain generated rustdoc (`cargo doc`) or docs.rs output."
                    .to_string(),
            )],
        },
        DocAttr::Bullet {
            level: 0,
            content: vec![DocAttr::Raw(
                "For build, rely on feature `cargo build --features inst` output."
                    .to_string(),
            )],
        },
        DocAttr::LineBreak,
    ]);
}
