// SPDX-License-Identifier: MPL-2.0
//
// Part of Auguth Labs open-source softwares.
// Built for the Rust Programming Language Ecosystem.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2026 Auguth Labs (OPC) Pvt Ltd, India

// ===============================================================================
// ````````````````````````````` FALLBACK-ERROR-SPACE ````````````````````````````
// ===============================================================================

//! Defines fallback and default error spaces for the crate.
//!
//! These are used when the consuming (user) crate does not define its own
//! error spaces. They provide stable, non-overlapping error ID ranges for
//! diagnostics generated by this library.

// ===============================================================================
// ``````````````````````````````````` IMPORTS ```````````````````````````````````
// ===============================================================================

use proc_macro2::Span;
use syn::{Ident, LitInt};

// --- Local-crate ----
use crate::{diagnostics, error_spaces, errors::ErrorMaintainers};

// ===============================================================================
// `````````````````````````````````` CONSTANTS ``````````````````````````````````
// ===============================================================================

/// Stable error ID space for this crate.
///
/// Defines structured, non-overlapping error ranges used to generate
/// consistent and reproducible diagnostics across the crate.
///
/// These IDs are intended to remain stable over time.
pub(crate) const NAMESPACE: &str = "PROC_SUITE";

// ===============================================================================
// ````````````````````````````````` DECLARATIONS ````````````````````````````````
// ===============================================================================

error_spaces! {
    space: NAMESPACE,
    maintain: ErrorMaintainers { mailto: None, git_host: None },

    /// Duplicate-related error IDs.
    pub(crate) enum DupError {
        range: 0..=999,
        variants: {
            /// Duplicate items found.
            Default,
            /// Duplicate identifiers in list.
            IdentList,
            /// Duplicate integer literals in list.
            IntList,
            /// Duplicate byte string literals in list.
            BStrList,
        }
    }

    /// General parsing error IDs.
    pub(crate) enum ParseError {
        range: 1000..=1999,
        variants: {
            /// Generic parse error.
            Default,
            /// Rust Ident parse error.
            Ident,
            /// Identifier list parse error.
            IdentList,
            /// Integer list parse error.
            IntList,
            /// Byte string list parse error.
            BStrList,
            /// Where Predicates Bounds list parse error.
            BoundsList,
            /// Expr list parse error.
            ExprList,
            /// Delimiter parse error.
            Delim,
            /// Parenthesized group parse error.
            ParenDelim,
            /// Braced group parse error.
            BraceDelim,
            /// Bracketed group parse error.
            BracketDelim,
            /// Key list parse error.
            KeyList,
            /// Value Groups list parse error.
            ValueGroup,
            /// Expr list group parse error.
            GroupExprList,
            /// Expr list group parse error.
            StmtList,
            /// Positive Literal Integer fits in `usize`
            PositiveUsize,
            /// Positive Literal Integer fits in `u32`
            PositiveU32,
            /// Positive Literal Integer fits in `u16`
            PositiveU16,
            /// Positive Literal Integer fits in `u8`
            PositiveU8,
        }
    }

    /// Key-value specific parsing error IDs.
    pub(crate) enum KeyParseError {
        range: 2000..=2999,
        variants: {
            /// Generic key-value parse error.
            Default,
            /// Expression list in key parse error.
            ExprList,
            /// Nested key list parse error.
            KeyList,
            /// Nested Value group lists parse error
            ValueGroup,
            /// Unexpected given key identifier from a allowed list
            UnexpectedKey,
            /// Duplicate Key Found in a Key List
            DuplicateKey,
            /// Missing a required key
            MissingKey,
            /// Expected key's value (homogeneous if list) is invalid
            InvalidValue,
            /// Expected key identifier is invalid
            InvalidKey,
            /// Expected key's values (heterogeneous) is invalid
            InvalidValues,
        }
    }

}

diagnostics!(
    space: ParseError,
    pub(crate) enum ProcParseErr {

        PositiveUsize {
            fields: {
                lit: LitInt,
            },
            msg: "expected a positive integer literal that fits in `usize`",
            tags: [InvalidInput],
            span: { tokens: lit },
        },
        PositiveU32 {
            fields: {
                lit: LitInt,
            },
            msg: "expected a positive integer literal that fits in `u32`",
            tags: [InvalidInput],
            span: { tokens: lit },
        },
        PositiveU16 {
            fields: {
                lit: LitInt,
            },
            msg: "expected a positive integer literal that fits in `u16`",
            tags: [InvalidInput],
            span: { tokens: lit },
        },
        PositiveU8 {
            fields: {
                lit: LitInt,
            },
            msg: "expected a positive integer literal that fits in `u8`",
            tags: [InvalidInput],
            span: { tokens: lit },
        },
    }
);

diagnostics!(
    space: KeyParseError,

    pub(super) enum KeyValueErrors {

        UnexpectedKey {
            fields: {
                found: Ident,
                allowed: String,
            },
            msg:
                "unexpected key found",
            tags: [Unsupported],
            span: { tokens: found },
            help: [
                {format!("expected any one of valid keys : `{}`", allowed)}
            ]
        },

        DuplicateKey {
            fields: {
                found: Ident,
            },
            msg:
                "found a duplicate key",
            tags: [Unsupported],
            span: { tokens: found },
            note: [
                "duplicate keys are not allowed, replace with a valid key identifier"
            ]
        },

        MissingKey {
            fields: {
                span: Span,
                require: Ident,
            },
            msg:
                format!("missing a required key `{}` in this key-list", require),
            tags: [Unsupported],
            span: { span: span },
            help: [
                {format!("add the following key `{}` to the key list", require)}
            ]
        },

        InvalidValue {
            fields: {
                key: Ident,
                expected: String,
                example: String,
                note: String,
            },
            msg:
                format!("key `{}` argument values expects {}", key, expected),
            tags: [Unsupported],
            span: { tokens: key },
            help: [
                {format!("example : {}", example)}
            ],
            note: [
                note.to_string(),
            ]
        },

        InvalidKey {
            fields: {
                found: Ident,
                require: Ident,
            },
            msg: "invalid key identifier found",
            tags: [Unsupported],
            span: { tokens: found },
            help: [
                {format!("expected key ident `{}` instead of `{}`", require, found)}
            ]
        },

    }
);
