// SPDX-License-Identifier: MPL-2.0
//
// Part of Auguth Labs open-source softwares.
// Built for the Rust Programming Language Ecosystem.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2026 Auguth Labs (OPC) Pvt Ltd, India

// ===============================================================================
// ````````````````````````````` INSTANCE AFFILIATES `````````````````````````````
// ===============================================================================

//! This module provides a way for one trait instance to refer to *other*
//! instantiations of the same trait on the same `Self` type.
//!
//! Affiliate relationships are encoded through typenum-backed counter tuples
//! and hidden associated items generated by proc macros.
//!
//! ## Why this exists
//!
//! Rust traits cannot naturally express relationships between multiple
//! instantiations of the same trait.
//!
//! For example, even if both exist:
//!
//! ```ignore
//! K<(U0, U0, U4)>
//! K<(U0, U0, U5)>
//! ```
//!
//! there is no built-in way for one instance to:
//!
//! - navigate to the other,
//! - prove the other exists,
//! - or encode structural relationships between them.
//!
//! This module works around that limitation by generating hidden associated
//! items directly inside the trait.
//!
//! ## What an affiliate is
//!
//! An **affiliate** is another instantiation of the same trait represented
//! through:
//!
//! - hidden associated counter items,
//! - and a hidden associated instance projection.
//!
//! Together, these reconstruct another valid instantiation of the original
//! trait with different counters.
//!
//! ```ignore
//! <Self as MyTrait<(U0, U0, U5)>>::NextAffiliateInstance
//! ```
//!
//! behaves like:
//!
//! ```ignore
//! MyTrait<(U0, U0, U6)>
//! ```
//!
//! while:
//!
//! ```ignore
//! <Self as MyTrait<(U0, U0, U5)>>::ReverseAffiliateInstance
//! ```
//!
//! behaves like:
//!
//! ```ignore
//! MyTrait<(U0, U0, U4)>
//! ```
//!
//! The exact meaning of an affiliate is determined by the affiliate family.
//!
//! ## Affiliate Families
//!
//! This module provides several affiliate families.
//!
//! ### Structural Affiliates
//!
//! Structural affiliates are mechanically derivable from the current counter
//! tuple.
//!
//! These are always locally determinable from the counter tuple.
//!
//! - [`ReverseAffiliate`]
//!     Structural reverse projection.
//!
//! - [`CeilAffiliate`]
//!     Structural canonicalization / jump-table projection.
//!
//! ### Semantic Affiliates
//!
//! Semantic affiliates requires instance graph relations to compute the counter.
//!
//! These describe relationships in the implementation graph rather than purely
//! structural counter transforms.
//!
//! - [`NextAffiliate`]
//!     Canonical semantic successor.
//!
//! - [`BackAffiliate`]
//!     Canonical semantic predecessor.
//!
//! - [`FloorAffiliates`]
//!     Canonical semantic representatives / floor projections (multiple).
//!
//! ### Checkers
//!
//! - [`AffiliateCountersChecker`]
//!     Defines a checkpoint to evaluate rogue
//!     (out of canonical-chain) instance implementations.
//!
//! ## Counter Tuples
//!
//! Affiliates operate over `typenum`-backed counter tuples rather than raw
//! const generics.
//!
//! ```ignore
//! (U0, U1, U5)
//! ```
//!
//! acts like a positional counter space.
//!
//! Affiliates transform or reinterpret those counters to navigate between
//! related trait instances.
//!
//! ## Affiliate Components
//!
//! Every affiliate family generates:
//!
//! - an affiliated counter projection,
//! - and an affiliated instance projection.
//!
//! The counter projection computes or stores the affiliated counter tuple,
//! while the instance projection reconstructs the corresponding trait
//! instantiation for the same `Self` type.
//!
//! ## Hidden Generated Items
//!
//! Each affiliate family injects hidden associated items into the trait:
//!
//! - affiliate counters
//! - affiliate instance projections
//!
//! The generated identifiers are deterministic random names known only
//! to this proc-macro crate.
//!
//! This prevents user code from forging affiliate transitions while allowing
//! implementation-side macros to reconstruct affiliate topology safely.
//!
//! ## Sum-Type Relationships
//!
//! Affiliate instance projections also preserve the associated-type equality
//! relationships established by [`crate::traits::sum`].
//!
//! When an affiliate reconstructs another instantiation of the same trait,
//! `#[sum]` associated types are carried into the reconstructed trait
//! instantiation as explicit associated-type equalities:
//!
//! ```ignore
//! MyTrait<AffiliateCounters, Value = Self::Value>
//! ```
//!
//! Thus, navigation between affiliated instances preserves the type identity
//! of sum-associated types rather than introducing a separate instance-specific
//! type. The affiliate relationship and the sum-type equality relationship are
//! therefore maintained together across recursive instance projections.
//!
//! ## What this enables
//!
//! Affiliates make it possible to:
//!
//! - navigate between related trait instances,
//! - define recursive instance families,
//! - express structural and semantic transitions,
//! - encode compile-time instance graphs,
//! - build jump-table style projections,
//! - and recursively access associated items across related instances.
//!
//! All of this works entirely at compile time without runtime values or
//! unstable language features.

// ===============================================================================
// ``````````````````````````````````` IMPORTS ```````````````````````````````````
// ===============================================================================

// --- Local Crate ---
use crate::{
    Extension, Extraction, Insertion, Instance, Transformation,
    traits::{counters::*, errors::AffiliateBugs, typenum::*, utils::*},
};

// --- Proc-Macro crates ---
use proc_macro2::TokenStream;
use quote::{ToTokens, format_ident};
use syn::{
    GenericArgument, GenericParam, ItemTrait, TraitItem, TraitItemConst, TraitItemType, Type,
    TypeParamBound, parse_quote, punctuated::Punctuated, token::Plus,
};

// --- Proc Suite ---
use proc_suite::{SupportCrate, misc::*};

// ===============================================================================
// `````````````````````````````````` AFFILIATES `````````````````````````````````
// ===============================================================================

/// Applies all affiliate families to a trait definition.
///
/// Affiliates allow one trait instance to reference *other* instances of the
/// same trait on the same `Self` type.
///
/// ```ignore
/// <Self as MyTrait<(U0, U0, U5)>>::NextAffiliateInstance
/// ```
///
/// behaves like:
///
/// ```ignore
/// MyTrait<(U0, U0, U6)>
/// ```
///
/// while:
///
/// ```ignore
/// <Self as MyTrait<(U0, U0, U5)>>::ReverseAffiliateInstance
/// ```
///
/// behaves like:
///
/// ```ignore
/// MyTrait<(U0, U0, U4)>
/// ```
///
/// This transformation injects the hidden associated items required for
/// affiliate-based instance navigation.
///
/// Generated items include:
///
/// - affiliate counter projections,
/// - affiliate instance projections,
///
/// ## Affiliate Families
///
/// - [`ReverseAffiliate`]
///     Structural reverse projection.
///
/// - [`CeilAffiliate`]
///     Structural jump-table / canonicalization projection.
///
/// - [`NextAffiliate`]
///     Semantic successor projection.
///
/// - [`BackAffiliate`]
///     Semantic predecessor projection.
///
/// - [`FloorAffiliates`]
///     Semantic canonical representatives / floor projections (per counter).
///
/// - [`AffiliateCountersChecker`]
///     Invariants Checker for rogue instance impls.
///
/// ## Sum-Type Relationships
///
/// Affiliate instance projections preserve the associated-type equality
/// relationships established by [`crate::traits::sum`].
///
/// When an affiliated instance is reconstructed, every `#[sum]` associated
/// type is carried into that instance as an explicit associated-type equality:
///
/// ```ignore
/// MyTrait<AffiliateCounters, Value = Self::Value>
/// ```
///
/// See the module-level documentation for more information about:
///
/// - affiliate semantics,
/// - structural vs semantic affiliates,
/// - and recursive instance navigation.
#[derive(Clone, Debug)]
pub(crate) struct InstanceTraitAffiliates;

impl Insertion<ItemTrait> for TraitItemType {
    fn raw_insert(&self, to: &mut ItemTrait, _: &()) -> Result<(), TokenStream> {
        to.items.push(TraitItem::Type(self.clone()));
        Ok(())
    }

    fn validate_inserted(
        _: Option<&Self>,
        _: &ItemTrait,
        _: Option<&()>,
    ) -> Result<(), TokenStream> {
        // We don't want to test syn internals
        Ok(())
    }
}

impl<'a> Transformation<ItemTrait, CounterParamsSlice<'a>> for InstanceTraitAffiliates {
    fn raw_transform(
        &self,
        transform: &mut ItemTrait,
        context: &CounterParamsSlice<'a>,
    ) -> Result<(), TokenStream> {
        ReverseAffiliate::checked_transform(&ReverseAffiliate, transform, &())?;
        CeilAffiliate::checked_transform(&CeilAffiliate, transform, &())?;
        NextAffiliate::checked_transform(&NextAffiliate, transform, &())?;
        BackAffiliate::checked_transform(&BackAffiliate, transform, &())?;
        FloorAffiliates::checked_transform(&FloorAffiliates, transform, context)?;
        AffiliateCountersChecker::checked_extend(&AffiliateCountersChecker, transform, &())?;
        Ok(())
    }

    fn validate_transform(
        &self,
        transform: &ItemTrait,
        context: Option<&CounterParamsSlice<'a>>,
    ) -> Result<(), TokenStream> {
        ReverseAffiliate::validate_transform(&ReverseAffiliate, transform, None)?;
        CeilAffiliate::validate_transform(&CeilAffiliate, transform, None)?;
        NextAffiliate::validate_transform(&NextAffiliate, transform, None)?;
        BackAffiliate::validate_transform(&BackAffiliate, transform, None)?;
        FloorAffiliates::validate_transform(&FloorAffiliates, transform, context)?;
        AffiliateCountersChecker::validate_extend(
            &AffiliateCountersChecker,
            None,
            transform,
            None,
        )?;
        Ok(())
    }
}

// ===============================================================================
// ```````````````````````````` AFFILIATE BOILERPLATE ````````````````````````````
// ===============================================================================

/// Defines an affiliate family whose relationships are resolved entirely
/// by implementation-side expansion.
macro_rules! define_affiliate {
    (
        affiliate {
            $(#[$affiliate_meta:meta])*
            $affiliate:ident
        },

        counters {
            $(#[$counters_meta:meta])*
            $counters:ident
        },

        instance {
            $(#[$instance_meta:meta])*
            $instance:ident
        },

        bugs: $bugs:ident $(,)?
    ) => {
        paste::paste! {
            $(#[$affiliate_meta])*
            #[derive(Clone, Debug)]
            pub(crate) struct $affiliate;

            impl Transformation<ItemTrait> for $affiliate {
                fn raw_transform(
                    &self,
                    transform: &mut ItemTrait,
                    context: &(),
                ) -> Result<(), TokenStream> {
                    $counters::checked_extend(
                        &$counters,
                        transform,
                        context,
                    )?;

                    $instance::checked_extend(
                        &$instance,
                        transform,
                        context,
                    )?;

                    Ok(())
                }

                fn validate_transform(
                    &self,
                    transform: &ItemTrait,
                    context: Option<&()>,
                ) -> Result<(), TokenStream> {
                    $counters::validate_extend(
                        &$counters,
                        None,
                        transform,
                        context,
                    )?;

                    $instance::validate_extend(
                        &$instance,
                        None,
                        transform,
                        context,
                    )?;

                    Ok(())
                }
            }

            $(#[$counters_meta])*
            #[derive(Clone, Debug)]
            pub(crate) struct $counters;

            impl Extension<TraitItemType, ItemTrait>
                for $counters
            {
                fn raw_extend(
                    &self,
                    _towards: &ItemTrait,
                    _: &(),
                ) -> Result<TraitItemType, TokenStream> {

                    let ident = gen_type_ident::<$counters>();

                    Ok(TraitItemType {
                        attrs: proc_suite::internal_code(),
                        ident,
                        default: None,
                        type_token: Default::default(),
                        generics: Default::default(),
                        colon_token: Default::default(),
                        bounds: Default::default(),
                        semi_token: Default::default(),
                    })
                }

                fn validate_extend(
                    &self,
                    item: Option<&TraitItemType>,
                    towards: &ItemTrait,
                    _: Option<&()>,
                ) -> Result<(), TokenStream> {
                    let expected_ident = gen_type_ident::<Self>();
                    let bounds = &[];

                    validate_trait_type! {
                        item: item,
                        towards: towards,

                        ident: expected_ident,

                        bounds: bounds => {
                            not_found:
                                $bugs::[<$affiliate Counters Missing>] {},
                            wrong_ident:
                                $bugs::[<$affiliate Counters InvalidIdent>] {},
                            has_generics:
                                $bugs::[<$affiliate Counters HasGenerics>] {},
                            bound_not_found:
                                $bugs::[<$affiliate Counters BoundNotFound>] {},
                        }
                    }
                }
            }

            $(#[$instance_meta])*
            #[derive(Clone, Debug)]
            pub(crate) struct $instance;

            impl Extension<TraitItemType, ItemTrait>
                for $instance
            {
                fn raw_extend(
                    &self,
                    towards: &ItemTrait,
                    _: &(),
                ) -> Result<TraitItemType, TokenStream> {
                    let ident = gen_type_ident::<Self>();

                    let trait_ident = &towards.ident;

                    let counters_generic =
                        gen_type_ident::<InstanceTraitTypeNumCounters>();

                    let counters_assoc: syn::Type = {
                        let ident =
                            gen_type_ident::<$counters>();

                        parse_quote!(Self::#ident)
                    };

                    let args =
                        towards.generics.params.iter().map(|param| {
                            match param {
                                GenericParam::Type(ty) => {
                                    if ty.ident == counters_generic {
                                        GenericArgument::Type(
                                            counters_assoc.clone()
                                        )
                                    } else {
                                        let ident = &ty.ident;
                                        parse_quote!(#ident)
                                    }
                                }

                                GenericParam::Lifetime(lt) => {
                                    let lifetime = &lt.lifetime;
                                    parse_quote!(#lifetime)
                                }

                                GenericParam::Const(cnst) => {
                                    let ident = &cnst.ident;
                                    parse_quote!(#ident)
                                }
                            }
                        });

                    let mut angle : syn::AngleBracketedGenericArguments = parse_quote!(<#(#args),*>);

                    let mut collect = Vec::new();
                    for item in &towards.items {
                        let TraitItem::Type(ty) = item else {
                            continue;
                        };

                        if !ty.attrs.iter().any(|attr| attr.path().is_ident("sum")) {
                            continue;
                        }

                        let ty_ident = &ty.ident;

                        collect.push(ty_ident.clone());
                    }

                    for ident in &collect {
                        angle.args.push(parse_quote!(#ident = Self::#ident));
                    }

                    let bound = parse_quote!(
                        #trait_ident #angle
                    );

                    let mut bounds =
                        Punctuated::<TypeParamBound, Plus>::new();

                    bounds.push(TypeParamBound::Trait(bound));

                    Ok(TraitItemType {
                        attrs: proc_suite::internal_code(),
                        ident,
                        default: None,
                        type_token: Default::default(),
                        generics: Default::default(),
                        colon_token: Default::default(),
                        bounds,
                        semi_token: Default::default(),
                    })
                }

                fn validate_extend(
                    &self,
                    item: Option<&TraitItemType>,
                    towards: &ItemTrait,
                    _: Option<&()>,
                ) -> Result<(), TokenStream> {
                    let expected_ident = gen_type_ident::<Self>();

                    validate_trait_type! {
                        item: item,
                        towards: towards,

                        ident: expected_ident,

                        bounds: Vec::<&syn::TraitBound>::new() => {
                            not_found:
                                $bugs::[<$affiliate Instance Missing>] {},
                            wrong_ident:
                                $bugs::[<$affiliate Instance InvalidIdent>] {},
                            has_generics:
                                $bugs::[<$affiliate Instance HasGenerics>] {},
                            bound_not_found:
                                $bugs::[<$affiliate Instance BoundNotFound>] {},
                        }
                    }?;

                    let trait_ident = &towards.ident;

                    let counters_generic =
                        gen_type_ident::<InstanceTraitTypeNumCounters>();

                    let counters_assoc: syn::Type = {
                        let ident =
                            gen_type_ident::<$counters>();

                        parse_quote!(Self::#ident)
                    };

                    let args =
                        towards.generics.params.iter().map(|param| {
                            match param {
                                GenericParam::Type(ty) => {
                                    if ty.ident == counters_generic {
                                        GenericArgument::Type(
                                            counters_assoc.clone()
                                        )
                                    } else {
                                        let ident = &ty.ident;
                                        parse_quote!(#ident)
                                    }
                                }

                                GenericParam::Lifetime(lt) => {
                                    let lifetime = &lt.lifetime;
                                    parse_quote!(#lifetime)
                                }

                                GenericParam::Const(cnst) => {
                                    let ident = &cnst.ident;
                                    parse_quote!(#ident)
                                }
                            }
                        });

                    let mut angle : syn::AngleBracketedGenericArguments = parse_quote!(<#(#args),*>);

                    let mut collect = Vec::new();
                    for item in &towards.items {
                        let TraitItem::Type(ty) = item else {
                            continue;
                        };

                        if !ty.attrs.iter().any(|attr| attr.path().is_ident("sum")) {
                            continue;
                        }

                        let ty_ident = &ty.ident;

                        collect.push(ty_ident.clone());
                    }

                    for ident in &collect {
                        angle.args.push(parse_quote!(#ident = Self::#ident));
                    }


                    let sum_inst_item = towards.items.iter().find_map(|item| {
                        let TraitItem::Type(ty) = item else {
                            return None;
                        };

                        (ty.ident == expected_ident).then_some(ty)
                    });

                    let Some(sum_inst_item) = sum_inst_item else {
                        return Err($bugs::[<$affiliate Instance Missing>] {}.into());
                    };

                    let Some(trait_bound) = sum_inst_item.bounds.iter().find_map(|bound| {
                        let syn::TypeParamBound::Trait(bound) = bound else {
                            return None;
                        };

                        (bound.path.segments.last()?.ident == *trait_ident).then_some(bound)
                    }) else {
                        return Err($bugs::[<$affiliate Instance BoundNotFound>] {}.into());
                    };

                    let Some(segment) = trait_bound.path.segments.last() else {
                        return Err($bugs::[<$affiliate Instance BoundNotFound>] {}.into());
                    };

                    let syn::PathArguments::AngleBracketed(args) = &segment.arguments else {
                        return Err($bugs::[<$affiliate Instance BoundInvalid>] {}.into());
                    };

                    let expected_args = &angle.args;
                    let actual_args = &args.args;

                    if !(expected_args.len() <= actual_args.len()) {
                        return Err($bugs::[<$affiliate Instance BoundInvalid>] {}.into());
                    }

                    for (expected, actual) in expected_args.iter().zip(actual_args.iter()) {
                        if expected != actual {
                            return Err($bugs::[<$affiliate Instance BoundInvalid>] {}.into());
                        }
                    }

                    let actual_equalities = actual_args.iter().filter_map(|arg| {
                        let GenericArgument::AssocType(assoc) = arg else {
                            return None;
                        };

                        Some(assoc)
                    });

                    for ident in &collect {
                        let expected_type: Type = parse_quote!(Self::#ident);

                        let Some(_) = actual_equalities.clone().find(|assoc| {
                            assoc.ident == *ident && assoc.ty == expected_type
                        }) else {
                            return Err($bugs::[<$affiliate Instance BoundInvalid>] {}.into());
                        };
                    }

                    Ok(())

                }
            }
        }
    };
}

// ===============================================================================
// `````````````````````````````` REVERSE AFFILIATE ``````````````````````````````
// ===============================================================================

define_affiliate! {

    // ident: format_ident!{"Reverse"},

    affiliate {
        /// Builds all hidden trait items required for the **Reverse**
        /// affiliate family.
        ///
        /// For a general explanation of *affiliates*, see the module-level
        /// documentation.
        ///
        /// Reverse provides a deterministic structural notion of "moving
        /// backward" through a typenum-backed instance-counter space.
        ///
        /// Reverse:
        ///
        /// - never underflows,
        /// - is always well-formed,
        /// - preserves recursive reachability,
        /// - and can always be derived from the current counters.
        ///
        /// The true semantic predecessor of an instance belongs instead to
        /// the *Back* affiliate.
        ///
        /// ## Reverse Semantics
        ///
        /// Reverse locates the rightmost non-zero counter and decrements it.
        ///
        /// Examples:
        ///
        /// ```text
        /// [5]         -> [4]
        /// [3, 2]      -> [3, 1]
        /// [3, 0]      -> [2, 0]
        /// [0, 0, 0]   -> [0, 0, 0]
        /// ```
        ///
        /// Reverse is intentionally saturating and does not perform
        /// positional borrowing.
        ///
        /// ## Generated Items
        ///
        /// This affiliate injects:
        ///
        /// - [`ReverseAffiliateCounters`]
        ///     Computes the reverse counter tuple.
        ///
        /// - [`ReverseAffiliateInstance`]
        ///     Projects the current trait into its reverse-associated
        ///     instance.
        ///
        /// ## Why Reverse Always Works
        ///
        /// Because Reverse is saturating and instance spaces begin from a
        /// zeroth implementation, the generated reverse tuple always refers
        /// to an already-reachable instance for the same `Self` type.
        ReverseAffiliate
    },

    counters {
        /// Generates the reverse-affiliated counter projection.
        ///
        /// ```ignore
        /// type ReverseAffiliateCounters;
        /// ```
        ///
        /// Reverse expected implementation to decrement the rightmost
        /// non-zero counter while leaving all other counters unchanged.
        ///
        /// Examples:
        ///
        /// ```text
        /// (0,0,1) -> (0,0,0)
        /// (0,1,0) -> (0,0,0)
        /// (1,0,0) -> (0,0,0)
        /// (0,0,0) -> (0,0,0)
        /// ```
        ///
        /// This provides a deterministic compile-time proof that a reachable
        /// reverse instance exists.
        ReverseAffiliateCounters
    },

    instance {
        /// Generates the reverse-affiliated trait-instance projection.
        ///
        /// ```ignore
        /// type ReverseAffiliateInstance:
        ///     MyTrait<Self::ReverseAffiliateCounters>;
        /// ```
        ///
        /// This recursively proves that the reverse-associated instance also
        /// exists, allowing recursive access to associated items without
        /// manually reconstructing reverse counters.
        ///
        /// Additionally, preserves the associated-type equality relationships established by
        /// [`crate::traits::sum`] for `#[sum]` associated types.
        ///
        /// ## Example
        ///
        /// ```ignore
        /// trait Woo<Counters>
        /// where
        ///     Counters: DirectAffiliate<Counters, Reverse>,
        /// {
        ///     #[sum]
        ///     type Value;
        ///
        ///     const VALUE: u8;
        ///
        ///     type ReverseAffiliateCounters;
        ///
        ///     type ReverseAffiliateInstance:
        ///         Woo<Self::ReverseAffiliateCounters, Value = Self::Value>;
        /// }
        ///
        /// impl Woo<(U0, U0, U0)> for Test {
        ///     const VALUE: u8 = 0;
        ///
        ///     type ReverseAffiliateCounters = (U0, U0, U0);
        ///     type ReverseAffiliateInstance = Self;
        /// }
        ///
        /// impl Woo<(U0, U0, U1)> for Test {
        ///     const VALUE: u8 = 1;
        ///
        ///     type ReverseAffiliateCounters = (U0, U0, U0);
        ///     type ReverseAffiliateInstance = Self;
        /// }
        ///
        /// impl Woo<(U0, U1, U0)> for Test {
        ///     const VALUE: u8 = 10;
        ///
        ///     type ReverseAffiliateCounters = (U0, U0, U0);
        ///     type ReverseAffiliateInstance = Self;
        /// }
        ///
        /// let current = <Test as Woo<(U0, U1, U0)>>::VALUE;
        ///
        /// let reverse = <
        ///     <Test as Woo<(U0, U1, U0)>>::ReverseAffiliateInstance
        ///         as Woo<
        ///             <Test as Woo<(U0, U1, U0)>>::ReverseAffiliateCounters
        ///         >
        /// >::VALUE;
        ///
        /// assert_eq!(current, 10);
        /// assert_eq!(reverse, 0);
        /// ```
        ///
        /// This acts as:
        ///
        /// - a compile-time proof witness,
        /// - a reverse-navigation edge,
        /// - and a type-safe transition into reachable reverse instances.
        ReverseAffiliateInstance
    },

    bugs: AffiliateBugs,
}

// ===============================================================================
// ```````````````````````````````` CEIL AFFILIATE ```````````````````````````````
// ===============================================================================

define_affiliate! {

    // ident: format_ident!{"Ceil"},


    affiliate {
        /// Builds all hidden trait items required for the **Ceil** affiliate
        /// family.
        ///
        /// For a general explanation of *affiliates*, see the module-level
        /// documentation.
        ///
        /// The Ceil affiliate provides a deterministic, trait-level notion of
        /// "moving upward" through a typenum-backed instance-counter space.
        ///
        /// Importantly, Ceil is **not** a true arithmetic ceiling operation.
        ///
        /// Instead, it computes a structurally valid parent projection that:
        ///
        /// - always remains well-formed,
        /// - preserves recursive trait reachability,
        /// - avoids unbounded forward expansion,
        /// - and can be derived entirely from the current counter tuple.
        ///
        /// The operation intentionally collapses the **rightmost non-zero
        /// dimension** and all dimensions to its right back to zero.
        ///
        /// This forms a stable structural "ceiling" transition that moves toward
        /// canonicalized higher-level states without requiring knowledge of:
        ///
        /// - dimensional radix limits,
        /// - overflow semantics,
        /// - or implementation-defined successor topology.
        ///
        /// ## Ceil Counter Semantics
        ///
        /// Ceil operates by locating the **rightmost non-zero counter** and
        /// resetting it to zero.
        ///
        /// Examples:
        ///
        /// ```text
        /// [0,0,5]   -> [0,0,0]
        /// [0,3,0]   -> [0,0,0]
        /// [4,0,0]   -> [0,0,0]
        /// [1,2,7]   -> [1,2,0]
        /// [1,9,0]   -> [1,0,0]
        /// [0,0,0]   -> [0,0,0]
        /// ```
        ///
        /// This operation is intentionally saturating and structural rather than
        /// arithmetic.
        ///
        /// The goal is not to compute a mathematically exact ceiling, but rather
        /// to produce a deterministic, recursively reachable affiliated-forward
        /// projection.
        ///
        /// ## Generated Items
        ///
        /// This affiliate injects:
        ///
        /// - [`CeilAffiliateCounters`]
        ///     Computes the ceil-affiliated counter tuple.
        ///
        /// - [`CeilAffiliateInstance`]
        ///     Projects the current trait into its ceil-affiliated instance.
        ///
        /// ## Why Ceil Always Works
        ///
        /// Ceil does not require implementation-side instance graph semantics.
        ///
        /// Because the operation only collapses dimensions toward zero, the
        /// resulting counter tuple always refers to an already-reachable trait
        /// instance for the same `Self` type.
        ///
        /// This makes Ceil a stable deterministic structural affiliate.
        ///
        /// ## Relationship to Semantic Forward Navigation
        ///
        /// Ceil answers:
        ///
        /// > "What is the nearest structurally collapsed backward projection?"
        ///
        /// It does not answer:
        ///
        /// > "What is the true semantic parent of current instance?"
        CeilAffiliate
    },

    counters {
        /// Generates the ceil-affiliated counter projection for the current
        /// instance-counter tuple.
        ///
        /// Conceptually, the generated associated type behaves like:
        ///
        /// ```ignore
        /// type CeilAffiliateCounters;
        /// ```
        ///
        /// The generated counter tuple must represent a structurally collapsed
        /// projection of the current instance counters.
        ///
        /// Ceil affiliation operates by locating the rightmost non-zero counter
        /// and resetting it to zero.
        ///
        /// Examples:
        ///
        /// ```text
        /// (0,0,1) -> (0,0,0)
        /// (0,1,0) -> (0,0,0)
        /// (1,0,0) -> (0,0,0)
        /// (2,3,4) -> (2,3,0)
        /// (5,7,0) -> (5,0,0)
        /// (0,0,0) -> (0,0,0)
        /// ```
        ///
        /// This intentionally forms a deterministic structural projection rather
        /// than an arithmetic normalization rule.
        ///
        /// The generated associated type therefore acts as a compile-time proof
        /// that a structurally reachable ceil-affiliated instance exists.
        CeilAffiliateCounters
    },

    instance {
        /// Generates the ceil-affiliated trait-instance projection.
        ///
        /// Conceptually, the generated associated type behaves like:
        ///
        /// ```ignore
        /// type CeilAffiliateInstance:
        ///     MyTrait<Self::CeilAffiliateCounters>;
        /// ```
        ///
        /// This projection recursively constrains the current instance to prove
        /// that its ceil-affiliated instance also exists.
        ///
        /// As a result, associated items from the ceil projection can be accessed
        /// recursively without manually reconstructing the affiliated counter
        /// tuple.
        ///
        /// Additionally, preserves the associated-type equality relationships established by
        /// [`crate::traits::sum`] for `#[sum]` associated types.
        ///
        /// ```ignore
        /// trait Woo<Counters>
        /// where
        ///     Counters: DirectAffiliate<Counters, Ceil>,
        /// {
        ///     #[sum]
        ///     type Value;
        ///
        ///     const VALUE: u8;
        ///
        ///     type CeilAffiliateCounters;
        ///
        ///     type CeilAffiliateInstance:
        ///         Woo<Self::CeilAffiliateCounters, Value = Self::Value>;
        /// }
        ///
        /// impl Woo<(U0, U0, U0)> for Test {
        ///     const VALUE: u8 = 0;
        ///
        ///     type CeilAffiliateCounters = (U0, U0, U0);
        ///     type CeilAffiliateInstance = Self;
        /// }
        ///
        /// impl Woo<(U0, U0, U7)> for Test {
        ///     const VALUE: u8 = 7;
        ///
        ///     type CeilAffiliateCounters = (U0, U0, U0);
        ///     type CeilAffiliateInstance = Self;
        /// }
        ///
        /// impl Woo<(U0, U5, U0)> for Test {
        ///     const VALUE: u8 = 50;
        ///
        ///     type CeilAffiliateCounters = (U0, U0, U0);
        ///     type CeilAffiliateInstance = Self;
        /// }
        ///
        /// let current = <Test as Woo<(U0, U5, U0)>>::VALUE;
        ///
        /// let ceil = <
        ///     <Test as Woo<(U0, U5, U0)>>::CeilAffiliateInstance
        ///         as Woo<
        ///             <Test as Woo<(U0, U5, U0)>>::CeilAffiliateCounters
        ///         >
        /// >::VALUE;
        ///
        /// assert_eq!(current, 50);
        /// assert_eq!(ceil, 0);
        /// ```
        ///
        /// The caller never needs to manually reconstruct the affiliated counter
        /// transition because the generated projection already carries the
        /// required trait transition and proof relationship.
        ///
        /// The generated associated type therefore acts as:
        ///
        /// - a compile-time proof witness,
        /// - a recursive structural-navigation edge,
        /// - and a type-safe transition into structurally reachable
        ///   ceil-affiliated instances.
        CeilAffiliateInstance
    },

    bugs: AffiliateBugs,
}

// ===============================================================================
// ```````````````````````````````` NEXT AFFILIATE ```````````````````````````````
// ===============================================================================

define_affiliate! {

    affiliate {
        /// Builds all hidden trait items required for the **Next**
        /// affiliate family.
        ///
        /// For a general explanation of *affiliates*, see the module-level
        /// documentation.
        ///
        /// Next defines the canonical semantic successor relation over a
        /// typenum-backed implementation instance space.
        ///
        /// Unlike structural affiliates such as *Reverse* or *Ceil*, Next
        /// is implementation-defined and therefore cannot be recursively
        /// proven through trait bounds.
        ///
        /// ## Forward-Step Semantics
        ///
        /// Next treats the counter tuple as a positional number.
        ///
        /// Starting from the rightmost counter:
        ///
        /// - locate the first counter strictly less than `MAX`,
        /// - increment it,
        /// - reset all lower-order counters to zero,
        /// - and leave higher-order counters unchanged.
        ///
        /// Examples:
        ///
        /// ```text
        /// [4]         -> [5]
        /// [3, 1]      -> [3, 2]
        /// [3, MAX]    -> [4, 0]
        /// ```
        ///
        /// If all counters are already at `MAX`, the instance space is
        /// exhausted.
        ///
        /// ## Generated Items
        ///
        /// This affiliate injects:
        ///
        /// - [`NextAffiliateCounters`]
        ///     Computes the canonical successor counter tuple.
        ///
        /// - [`NextAffiliateInstance`]
        ///     Projects the current trait into its semantic successor
        ///     instance.
        ///
        /// ## Hidden Resolution
        ///
        /// Generated affiliate identifiers are deterministic random symbols
        /// known only to this proc-macro crate.
        ///
        /// This prevents user code from forging affiliate transitions while
        /// allowing implementation-side macros to reconstruct successor
        /// topology safely.
        NextAffiliate
    },

    counters {
        /// Generates the canonical semantic successor counter tuple.
        ///
        /// ```ignore
        /// type NextAffiliateCounters =
        ///     /* next counter tuple */;
        /// ```
        ///
        /// The tuple is computed using positional forward-stepping
        /// semantics.
        ///
        /// Examples:
        ///
        /// ```text
        /// (0,0,0) -> (0,0,1)
        /// (0,0,9) -> (0,1,0)
        /// (0,4,9) -> (0,5,0)
        /// (8,9,9) -> (9,0,0)
        /// ```
        ///
        /// Unlike structural affiliates, existence of the generated
        /// successor is validated on the implementation side rather than
        /// through recursive trait bounds.
        NextAffiliateCounters
    },

    instance {
        /// Generates the semantic next-instance projection.
        ///
        /// ```ignore
        /// type NextAffiliateInstance:
        ///     MyTrait<Self::NextAffiliateCounters>;
        /// ```
        ///
        /// Unlike structural affiliates, this projection does not recursively
        /// prove that the next instance exists.
        ///
        /// Instead, it represents a semantic successor edge resolved during
        /// implementation-side expansion.
        ///
        /// Additionally, preserves the associated-type equality relationships established by
        /// [`crate::traits::sum`] for `#[sum]` associated types.
        ///
        /// ## Example
        ///
        /// ```ignore
        /// trait Woo<Counters> {
        ///     #[sum]
        ///     type Value;
        ///
        ///     const VALUE: u8;
        ///
        ///     type NextAffiliateCounters;
        ///
        ///     type NextAffiliateInstance:
        ///         Woo<Self::NextAffiliateCounters, Value = Self::Value>;
        /// }
        ///
        /// impl Woo<(U0, U0, U0)> for Test {
        ///     const VALUE: u8 = 0;
        ///
        ///     type NextAffiliateCounters = (U0, U0, U1);
        ///     type NextAffiliateInstance = Self;
        /// }
        ///
        /// impl Woo<(U0, U0, U1)> for Test {
        ///     const VALUE: u8 = 1;
        ///
        ///     type NextAffiliateCounters = (U0, U1, U0);
        ///     type NextAffiliateInstance = Self;
        /// }
        ///
        /// impl Woo<(U0, U1, U0)> for Test {
        ///     const VALUE: u8 = 2;
        ///
        ///     type NextAffiliateCounters = (U0, U1, U1);
        ///     type NextAffiliateInstance = Self;
        /// }
        ///
        /// let current = <Test as Woo<(U0, U0, U1)>>::VALUE;
        ///
        /// let next = <
        ///     <Test as Woo<(U0, U0, U1)>>::NextAffiliateInstance
        ///         as Woo<
        ///             <Test as Woo<(U0, U0, U1)>>::NextAffiliateCounters
        ///         >
        /// >::VALUE;
        ///
        /// assert_eq!(current, 1);
        /// assert_eq!(next, 2);
        /// ```
        ///
        /// The generated projection already carries the required successor
        /// relationship, so callers never need to manually reconstruct the
        /// transition.
        ///
        /// This acts as:
        ///
        /// - a semantic successor edge,
        /// - a proc-macro-resolvable affiliate witness,
        /// - and a type-safe projection into the next instance.
        NextAffiliateInstance
    },

    bugs: AffiliateBugs,
}

// ===============================================================================
// ```````````````````````````````` BACK AFFILIATE ```````````````````````````````
// ===============================================================================

define_affiliate! {

    affiliate {
        /// Builds all hidden trait items required for the **Back**
        /// affiliate family.
        ///
        /// For a general explanation of *affiliates*, see the module-level
        /// documentation.
        ///
        /// Back represents the true semantic predecessor relation between
        /// implementation instances.
        ///
        /// Unlike structural affiliates such as *Reverse* or *Ceil*, Back
        /// is implementation-defined and cannot be derived mechanically from
        /// the current counters.
        ///
        /// ## Predecessor Semantics
        ///
        /// Some implementations may use simple lexicographic predecessors:
        ///
        /// ```text
        /// [0,1,5] -> [0,1,4]
        /// ```
        ///
        /// while others may require domain-specific transitions:
        ///
        /// ```text
        /// current:
        ///     [0,1,0]
        ///
        /// Reverse:
        ///     [0,0,0]
        ///
        /// Back:
        ///     [0,0,X]
        /// ```
        ///
        /// where `X` is implementation-defined.
        ///
        /// ## Generated Items
        ///
        /// This affiliate injects:
        ///
        /// - [`BackAffiliateCounters`]
        ///     Stores predecessor counters.
        ///
        /// - [`BackAffiliateInstance`]
        ///     Projects the current trait into its predecessor instance.
        ///
        /// ## Relationship to Reverse
        ///
        /// Reverse answers:
        ///
        /// > "What structurally reachable reverse always exists?"
        ///
        /// Back instead answers:
        ///
        /// > "What is the actual semantic predecessor?"
        ///
        /// ## Hidden Resolution
        ///
        /// Generated affiliate identifiers are deterministic random symbols
        /// known only to this proc-macro crate.
        ///
        /// This prevents user code from forging affiliate transitions while
        /// allowing implementation-side macros to reconstruct predecessor
        /// topology safely.
        BackAffiliate
    },

    counters {
        /// Generates the semantic predecessor counter projection.
        ///
        /// ```ignore
        /// type BackAffiliateCounters =
        ///     /* implementation-defined counters */;
        /// ```
        ///
        /// Unlike structural affiliates, predecessor counters are supplied
        /// entirely by the implementation.
        ///
        /// Examples:
        ///
        /// ```text
        /// (0,1,5) -> (0,1,4)
        /// (0,1,0) -> (0,0,X)
        /// ```
        ///
        /// where `X` is implementation-defined.
        ///
        /// This acts as the compile-time representation of the semantic
        /// predecessor counters.
        BackAffiliateCounters
    },

    instance {
        /// Generates the semantic predecessor-instance projection.
        ///
        /// ```ignore
        /// type BackAffiliateInstance:
        ///     MyTrait<Self::BackAffiliateCounters>;
        /// ```
        ///
        /// Unlike structural affiliates, this projection does not recursively
        /// prove predecessor existence.
        ///
        /// Instead, it represents an implementation-defined predecessor
        /// transition resolved during implementation-side expansion.
        ///
        /// Additionally, preserves the associated-type equality relationships established by
        /// [`crate::traits::sum`] for `#[sum]` associated types.
        ///
        /// ## Example
        ///
        /// ```ignore
        /// trait Woo<Counters> {
        ///     #[sum]
        ///     type Value;
        ///
        ///     const VALUE: u8;
        ///
        ///     type BackAffiliateCounters;
        ///
        ///     type BackAffiliateInstance:
        ///         Woo<Self::BackAffiliateCounters, Value = Self::Value>;
        /// }
        ///
        /// impl Woo<(U0, U0, U0)> for Test {
        ///     const VALUE: u8 = 0;
        ///
        ///     type BackAffiliateCounters = (U0, U0, U0);
        ///     type BackAffiliateInstance = Self;
        /// }
        ///
        /// // ... intermediate instances ...
        ///
        /// impl Woo<(U0, U0, U9)> for Test {
        ///     const VALUE: u8 = 9;
        ///
        ///     type BackAffiliateCounters = (U0, U0, U8);
        ///     type BackAffiliateInstance = Self;
        /// }
        ///
        /// impl Woo<(U0, U1, U0)> for Test {
        ///     const VALUE: u8 = 10;
        ///
        ///     type BackAffiliateCounters = (U0, U0, U9);
        ///     type BackAffiliateInstance = Self;
        /// }
        ///
        /// let current = <Test as Woo<(U0, U1, U0)>>::VALUE;
        ///
        /// let previous = <
        ///     <Test as Woo<(U0, U1, U0)>>::BackAffiliateInstance
        ///         as Woo<
        ///             <Test as Woo<(U0, U1, U0)>>::BackAffiliateCounters
        ///         >
        /// >::VALUE;
        ///
        /// assert_eq!(current, 10);
        /// assert_eq!(previous, 9);
        /// ```
        ///
        /// The generated projection already carries the required predecessor
        /// relationship, so callers never need to manually reconstruct the
        /// transition.
        ///
        /// This acts as:
        ///
        /// - a semantic predecessor edge,
        /// - a proc-macro-resolvable affiliate witness,
        /// - and a type-safe projection into the previous instance.
        BackAffiliateInstance
    },

    bugs: AffiliateBugs,
}

// ===============================================================================
// ``````````````````````````````` FLOOR AFFILIATE ```````````````````````````````
// ===============================================================================

/// Builds all hidden trait items required for the **Floor**
/// affiliate family.
///
/// For a general explanation of *affiliates*, see the module-level
/// documentation.
///
/// Floor represents the semantic boundary relation of an individual
/// counter dimension.
///
/// Unlike structural affiliates such as *Reverse* or *Ceil*, Floor
/// is implementation-defined and cannot be derived mechanically from
/// the current counters.
///
/// ## Boundary Semantics
///
/// Every counter dimension may have its own semantic boundary.
///
/// Consider:
///
/// ```text
/// [Region, Product]
/// ```
///
/// The boundary reached by traversing the `Region` dimension may be
/// different from the boundary reached by traversing the `Product`
/// dimension.
///
/// Consequently a single instance may participate in multiple floor
/// relationships simultaneously.
///
/// Floor therefore operates per counter dimension rather than over
/// the counter tuple as a whole.
///
/// ## Relationship to Ceil
///
/// Floor acts as the semantic counterpart to the structural *Ceil*
/// affiliate.
///
/// ```text
/// Next  <-> Back
/// Ceil  <-> Floor
/// ```
///
/// where:
///
/// - *Next* and *Back* traverse semantic adjacency,
/// - *Ceil* provides structural canonicalization,
/// - and *Floor* provides semantic boundary navigation.
///
/// ## Generated Items
///
/// For every counter dimension this affiliate injects:
///
/// - a floor-counter projection,
/// - and a floor-instance projection.
///
/// Each pair represents the semantic boundary associated with a
/// particular counter dimension.
///
/// ## Hidden Resolution
///
/// Generated affiliate identifiers are deterministic random symbols
/// known only to this proc-macro crate.
///
/// This prevents user code from forging affiliate transitions while
/// allowing implementation-side macros to reconstruct semantic
/// boundary topology safely.
#[derive(Clone, Debug)]
pub(crate) struct FloorAffiliates;

impl<'a> Transformation<ItemTrait, CounterParamsSlice<'a>> for FloorAffiliates {
    fn raw_transform(
        &self,
        transform: &mut ItemTrait,
        context: &CounterParamsSlice<'a>,
    ) -> Result<(), TokenStream> {
        FloorAffiliatesCounters::checked_extend(&FloorAffiliatesCounters, transform, context)?;

        FloorAffiliatesInstances::checked_extend(&FloorAffiliatesInstances, transform, context)?;

        Ok(())
    }

    fn validate_transform(
        &self,
        transform: &ItemTrait,
        context: Option<&CounterParamsSlice<'a>>,
    ) -> Result<(), TokenStream> {
        FloorAffiliatesCounters::validate_extend(
            &FloorAffiliatesCounters,
            None,
            transform,
            context,
        )?;

        FloorAffiliatesInstances::validate_extend(
            &FloorAffiliatesInstances,
            None,
            transform,
            context,
        )?;

        Ok(())
    }
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// ``````````````````````````` FLOOR AFFILIATE COUNTERS ``````````````````````````
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/// Generates the semantic floor-counter projection.
///
/// ```ignore
/// type FloorAffiliatesCounters_N =
///     /* implementation-defined boundary counters */;
/// ```
///
/// Unlike structural affiliates, floor counters are supplied
/// entirely by the implementation.
///
/// A separate floor-counter projection exists for every counter
/// dimension.
///
/// ## Example
///
/// Consider:
///
/// ```text
/// [Category, Variant]
/// ```
///
/// The semantic boundary associated with `Category` may differ from
/// the semantic boundary associated with `Variant`.
///
/// Therefore:
///
/// ```text
/// FloorAffiliatesCounters_0
/// FloorAffiliatesCounters_1
/// ```
///
/// may resolve to different counter tuples even when evaluated from
/// the same instance.
///
/// This acts as the compile-time representation of the semantic
/// boundary counters associated with a specific counter dimension.
#[derive(Clone, Debug)]
pub(crate) struct FloorAffiliatesCounters;

impl<'a> Extension<Vec<TraitItemType>, ItemTrait, CounterParamsSlice<'a>>
    for FloorAffiliatesCounters
{
    fn raw_extend(
        &self,
        _towards: &ItemTrait,
        context: &CounterParamsSlice<'a>,
    ) -> Result<Vec<TraitItemType>, TokenStream> {
        let mut collect = Vec::new();
        for c in context.iter() {
            let ident = gen_type_ident_with_suffix::<FloorAffiliatesCounters>(Some(
                c.generic_index.to_string().as_bytes(),
            ));

            let crate_of = Instance::support_crate();

            let mut bounds = Punctuated::<TypeParamBound, Plus>::new();

            let mut make_affiliate_bound = |afl| {
                let bound = parse_quote!(
                    #crate_of::DirectAffiliate<
                        #crate_of::#afl
                    >
                );

                bounds.push(TypeParamBound::Trait(bound));
            };

            make_affiliate_bound(format_ident!("Reverse"));

            make_affiliate_bound(format_ident!("Ceil"));

            collect.push(TraitItemType {
                attrs: proc_suite::internal_code(),
                ident,
                default: None,
                type_token: Default::default(),
                generics: Default::default(),
                colon_token: Default::default(),
                bounds,
                semi_token: Default::default(),
            })
        }
        Ok(collect)
    }

    fn validate_extend(
        &self,
        item: Option<&Vec<TraitItemType>>,
        towards: &ItemTrait,
        context: Option<&CounterParamsSlice<'a>>,
    ) -> Result<(), TokenStream> {
        let extracted;
        let counters = match context {
            Some(c) => c,
            None => {
                extracted = CounterParams::checked_extract(towards, &None)?;
                extracted.as_slice().as_ref().as_ref()
            }
        };

        for c in counters.iter() {
            let expected_ident =
                gen_type_ident_with_suffix::<Self>(Some(c.generic_index.to_string().as_bytes()));

            let crate_of = Instance::support_crate();

            let make_affiliate_bound = |afl| -> syn::TraitBound {
                parse_quote!(
                    #crate_of::DirectAffiliate<
                        #crate_of::#afl
                    >
                )
            };

            let rev_bound = make_affiliate_bound(format_ident!("Reverse"));

            let ceil_bound = make_affiliate_bound(format_ident!("Ceil"));

            let bounds = &[rev_bound, ceil_bound];

            validate_trait_types! {
                items: item,
                towards: towards,

                ident: expected_ident,

                bounds: bounds => {
                    not_found:
                        AffiliateBugs::
                            FloorAffiliatesCountersMissing {},
                    wrong_ident:
                        AffiliateBugs::
                            FloorAffiliatesCountersInvalidIdent {},
                    has_generics:
                        AffiliateBugs::
                            FloorAffiliatesCountersHasGenerics {},
                    bound_not_found:
                        AffiliateBugs::
                            FloorAffiliatesCountersBoundNotFound {},
                }
            };
        }
        Ok(())
    }
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// `````````````````````````` FLOOR AFFILIATE INSTANCES ``````````````````````````
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/// Generates the semantic floor-instance projection.
///
/// ```ignore
/// type FloorAffiliatesInstances_N:
///     MyTrait<Self::FloorAffiliatesCounters_N>;
/// ```
///
/// Unlike structural affiliates, this projection does not recursively
/// prove floor existence.
///
/// Instead, it represents an implementation-defined semantic
/// boundary transition resolved during implementation-side expansion.
///
/// Additionally, preserves the associated-type equality relationships established by
/// [`crate::traits::sum`] for `#[sum]` associated types.
///
/// ## Example
///
/// ```ignore
/// trait Woo<Counters> {
///     #[sum]
///     type Value;
///
///     type FloorAffiliatesCounters_0;
///     type FloorAffiliatesInstances_0:
///         Woo<Self::FloorAffiliatesCounters_0, Value = Self::Value>;
///
///     type FloorAffiliatesCounters_1;
///     type FloorAffiliatesInstances_1:
///         Woo<Self::FloorAffiliatesCounters_1, Value = Self::Value>;
/// }
/// ```
///
/// A single instance may expose multiple floor projections because
/// different counter dimensions may terminate at different semantic
/// boundaries.
///
/// The generated projection already carries the required boundary
/// relationship, so callers never need to manually reconstruct the
/// transition.
///
/// This acts as:
///
/// - a semantic boundary edge,
/// - a proc-macro-resolvable affiliate witness,
/// - and a type-safe projection into the floor-associated instance
///   of a particular counter dimension.
#[derive(Clone, Debug)]
pub(crate) struct FloorAffiliatesInstances;

impl<'a> Extension<Vec<TraitItemType>, ItemTrait, CounterParamsSlice<'a>>
    for FloorAffiliatesInstances
{
    fn raw_extend(
        &self,
        towards: &ItemTrait,
        context: &CounterParamsSlice<'a>,
    ) -> Result<Vec<TraitItemType>, TokenStream> {
        let mut collect = Vec::new();
        for c in context.iter() {
            let gen_idx_str = c.generic_index.to_string();
            let gen_idx_byes = gen_idx_str.as_bytes();

            let ident = gen_type_ident_with_suffix::<Self>(Some(gen_idx_byes));

            let trait_ident = &towards.ident;

            let counters_generic = gen_type_ident::<InstanceTraitTypeNumCounters>();

            let counters_assoc: syn::Type = {
                let ident =
                    gen_type_ident_with_suffix::<FloorAffiliatesCounters>(Some(gen_idx_byes));

                parse_quote!(Self::#ident)
            };

            let args = towards.generics.params.iter().map(|param| match param {
                GenericParam::Type(ty) => {
                    if ty.ident == counters_generic {
                        GenericArgument::Type(counters_assoc.clone())
                    } else {
                        let ident = &ty.ident;

                        parse_quote!(#ident)
                    }
                }

                GenericParam::Lifetime(lt) => {
                    let lifetime = &lt.lifetime;

                    parse_quote!(#lifetime)
                }

                GenericParam::Const(cnst) => {
                    let ident = &cnst.ident;

                    parse_quote!(#ident)
                }
            });

            let mut angle: syn::AngleBracketedGenericArguments = parse_quote!(<#(#args),*>);

            let mut sums = Vec::new();
            for item in &towards.items {
                let TraitItem::Type(ty) = item else {
                    continue;
                };

                if !ty.attrs.iter().any(|attr| attr.path().is_ident("sum")) {
                    continue;
                }

                let ty_ident = &ty.ident;

                sums.push(ty_ident.clone());
            }

            for ident in &sums {
                angle.args.push(parse_quote!(#ident = Self::#ident));
            }

            let bound = parse_quote!(
                #trait_ident #angle
            );

            let mut bounds = Punctuated::<TypeParamBound, Plus>::new();

            bounds.push(TypeParamBound::Trait(bound));

            collect.push(TraitItemType {
                attrs: proc_suite::internal_code(),
                ident,
                default: None,
                type_token: Default::default(),
                generics: Default::default(),
                colon_token: Default::default(),
                bounds,
                semi_token: Default::default(),
            })
        }
        Ok(collect)
    }

    fn validate_extend(
        &self,
        item: Option<&Vec<TraitItemType>>,
        towards: &ItemTrait,
        context: Option<&CounterParamsSlice<'a>>,
    ) -> Result<(), TokenStream> {
        let extracted;
        let counters = match context {
            Some(c) => c,
            None => {
                extracted = CounterParams::checked_extract(towards, &None)?;
                extracted.as_slice().as_ref().as_ref()
            }
        };

        for c in counters.iter() {
            let gen_idx_str = c.generic_index.to_string();
            let gen_idx_byes = gen_idx_str.as_bytes();

            let expected_ident = gen_type_ident_with_suffix::<Self>(Some(gen_idx_byes));

            validate_trait_types! {
                items: item,
                towards: towards,

                ident: expected_ident,

                bounds: Vec::<&syn::TraitBound>::new() => {
                    not_found:
                        AffiliateBugs::
                            FloorAffiliatesInstancesMissing {},
                    wrong_ident:
                        AffiliateBugs::
                            FloorAffiliatesInstancesInvalidIdent {},
                    has_generics:
                        AffiliateBugs::
                            FloorAffiliatesInstancesHasGenerics {},
                    bound_not_found:
                        AffiliateBugs::
                            FloorAffiliatesInstancesBoundNotFound {},
                }
            };

            let trait_ident = &towards.ident;

            let counters_generic = gen_type_ident::<InstanceTraitTypeNumCounters>();

            let counters_assoc: syn::Type = {
                let ident =
                    gen_type_ident_with_suffix::<FloorAffiliatesCounters>(Some(gen_idx_byes));

                parse_quote!(Self::#ident)
            };

            let args = towards.generics.params.iter().map(|param| match param {
                GenericParam::Type(ty) => {
                    if ty.ident == counters_generic {
                        GenericArgument::Type(counters_assoc.clone())
                    } else {
                        let ident = &ty.ident;

                        parse_quote!(#ident)
                    }
                }

                GenericParam::Lifetime(lt) => {
                    let lifetime = &lt.lifetime;

                    parse_quote!(#lifetime)
                }

                GenericParam::Const(cnst) => {
                    let ident = &cnst.ident;

                    parse_quote!(#ident)
                }
            });

            let mut angle: syn::AngleBracketedGenericArguments = parse_quote!(<#(#args),*>);

            let mut collect = Vec::new();
            for item in &towards.items {
                let TraitItem::Type(ty) = item else {
                    continue;
                };

                if !ty.attrs.iter().any(|attr| attr.path().is_ident("sum")) {
                    continue;
                }

                let ty_ident = &ty.ident;

                collect.push(ty_ident.clone());
            }

            for ident in &collect {
                angle.args.push(parse_quote!(#ident = Self::#ident));
            }

            let sum_inst_item = towards.items.iter().find_map(|item| {
                let TraitItem::Type(ty) = item else {
                    return None;
                };

                (ty.ident == expected_ident).then_some(ty)
            });

            let Some(sum_inst_item) = sum_inst_item else {
                return Err(AffiliateBugs::FloorAffiliatesInstancesMissing {}.into());
            };

            let Some(trait_bound) = sum_inst_item.bounds.iter().find_map(|bound| {
                let syn::TypeParamBound::Trait(bound) = bound else {
                    return None;
                };

                (bound.path.segments.last()?.ident == *trait_ident).then_some(bound)
            }) else {
                return Err(AffiliateBugs::FloorAffiliatesInstancesBoundNotFound {}.into());
            };

            let Some(segment) = trait_bound.path.segments.last() else {
                return Err(AffiliateBugs::FloorAffiliatesInstancesBoundNotFound {}.into());
            };

            let syn::PathArguments::AngleBracketed(args) = &segment.arguments else {
                return Err(AffiliateBugs::FloorAffiliatesInstancesBoundInvalid {}.into());
            };

            let expected_args = &angle.args;
            let actual_args = &args.args;

            if !(expected_args.len() <= actual_args.len()) {
                return Err(AffiliateBugs::FloorAffiliatesInstancesBoundInvalid {}.into());
            }

            for (expected, actual) in expected_args.iter().zip(actual_args.iter()) {
                if expected != actual {
                    return Err(AffiliateBugs::FloorAffiliatesInstancesBoundInvalid {}.into());
                }
            }

            let actual_equalities = actual_args.iter().filter_map(|arg| {
                let GenericArgument::AssocType(assoc) = arg else {
                    return None;
                };

                Some(assoc)
            });

            for ident in &collect {
                let expected_type: Type = parse_quote!(Self::#ident);

                let Some(_) = actual_equalities
                    .clone()
                    .find(|assoc| assoc.ident == *ident && assoc.ty == expected_type)
                else {
                    return Err(AffiliateBugs::FloorAffiliatesInstancesBoundInvalid {}.into());
                };
            }
        }
        Ok(())
    }
}

// ===============================================================================
// ```````````````````` AFFILIATE COUNTERS CHECKER (FROM IMPL) ```````````````````
// ===============================================================================

/// Builds a hidden implementation-side consistency checker for affiliate
/// counter relationships.
///
/// This item exists to validate that implementation-defined affiliate
/// counters form a coherent instance graph.
///
/// Unlike structural affiliates such as *Reverse* and *Ceil*, semantic
/// affiliates such as *Next*, *Back*, and *Floor* are supplied by
/// implementation-side expansion.
///
/// Consequently, the proc-macro cannot assume those relationships are
/// internally consistent.
///
/// ## Canonical Chain Validation
///
/// The generated checker allows implementation-side expansion to verify
/// that semantic affiliate relationships form a single canonical
/// predecessor/successor chain.
///
/// ```text
/// current
///     == back(next(current))
///
/// current
///     == next(back(current))
/// ```
///
/// whenever both neighboring instances exist.
///
/// These invariants ensure that:
///
/// - successor relationships are reversible,
/// - predecessor relationships are reversible,
/// - affiliate transitions remain internally consistent,
/// - and no rogue instance implementations exist outside the canonical
///   instance graph.
///
/// ## Why this exists
///
/// Structural affiliates are derived directly from the current counters
/// and therefore cannot diverge.
///
/// Semantic affiliates are different.
///
/// Since implementations are responsible for supplying:
///
/// - `NextAffiliateCounters`,
/// - `BackAffiliateCounters`,
/// - `FloorAffiliateCounters`,
/// - and their corresponding instance projections,
///
/// invalid affiliate relationships could otherwise create:
///
/// - disconnected instance chains,
/// - multiple predecessors,
/// - multiple successors,
/// - unreachable instances,
/// - or contradictory affiliate topologies.
///
/// The generated checker provides a compile-time assertion point used by
/// implementation-side expansion to validate those relationships.
///
/// ## Generated Item
///
/// ```ignore
/// #[doc(hidden)]
/// const __AffiliateCountersChecker: ();
/// ```
///
/// Implementation-side expansion resolves this unit constant into a
/// collection of compile-time assertions verifying affiliate graph
/// consistency.
///
/// The trait-side declaration merely reserves a location for those
/// assertions.
#[derive(Clone, Debug)]
pub(crate) struct AffiliateCountersChecker;

impl Extension<TraitItemConst, ItemTrait> for AffiliateCountersChecker {
    fn raw_extend(&self, _: &ItemTrait, _: &()) -> Result<TraitItemConst, TokenStream> {
        let ident = gen_const_ident::<Self>();
        let ty = parse_quote!(());
        let item = TraitItemConst {
            attrs: proc_suite::internal_code(),
            ident,
            default: None,
            ty,
            const_token: Default::default(),
            generics: Default::default(),
            colon_token: Default::default(),
            semi_token: Default::default(),
        };
        Ok(item)
    }

    fn validate_extend(
        &self,
        item: Option<&TraitItemConst>,
        towards: &ItemTrait,
        _: Option<&()>,
    ) -> Result<(), TokenStream> {
        let ident = gen_const_ident::<Self>();
        let expected_ty: Type = parse_quote!(());

        validate_trait_const! {
            item: item,
            towards: towards,
            ident: ident,
            ty: expected_ty,
            expr: None => {
                not_found: AffiliateBugs::AffiliateCountersCheckerNotFound {},
                wrong_ident: AffiliateBugs::AffiliateCountersCheckerWrongIdent {},
                wrong_ty: AffiliateBugs::AffiliateCountersCheckerNotUnitType {},
                has_generics: AffiliateBugs::AffiliateCountersCheckerHasGenerics {},
                has_expr: AffiliateBugs::AffiliateCountersCheckerHasExpr {},
            }
        }
    }
}
