// SPDX-License-Identifier: MPL-2.0
//
// Part of Auguth Labs open-source softwares.
// Built for the Rust Programming Language Ecosystem.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2026 Auguth Labs (OPC) Pvt Ltd, India

// ===============================================================================
// ``````````````````````````` INSTANCE TYPENUM COUNTER ``````````````````````````
// ===============================================================================

//! Rewrites extracted instance-counter const generics into the synthesized
//! [`InstanceTraitTypeNumCounters`] type parameter.
//!
//! This transformation removes all extracted counter const generics from an
//! [`ItemTrait`] while preserving all other generics unchanged. The resulting
//! type-level representation is used by later expansion stages to perform
//! instance-counter computation through typenum-based machinery on stable Rust.
//!
//! ## Example
//!
//! Given:
//!
//! ```ignore
//! #[trait_instance(A, C)]
//! trait Example<const A: u8, const B: usize, const C: u8> {}
//! ```
//!
//! extraction identifies:
//!
//! ```text
//! A, C
//! ```
//!
//! and this transformation rewrites the trait into:
//!
//! ```ignore
//! trait Example<__TypeNumCounters, const B: usize> {}
//! ```
//!
//! where `__TypeNumCounters` is an internal synthesized type parameter
//! generated by the [`InstanceTraitTypeNumCounters`] [`Transformation`] pass.

// ===============================================================================
// ``````````````````````````````````` IMPORTS ```````````````````````````````````
// ===============================================================================

// --- Proc-Macro crates ---
use proc_macro2::TokenStream;
use syn::{GenericParam, ItemTrait, TypeParam, punctuated::Punctuated, token::Comma};

// --- Local Crate ---
use crate::{
    Extraction, Transformation,
    traits::{
        counters::*,
        errors::{TypeNumCountersBugs, TypeNumErrors},
    },
};

// --- Proc-Suite ---
use proc_suite::misc::*;

// ===============================================================================
// ``````````````````````` TYPENUM COUNTERS TRANSFORMATION ```````````````````````
// ===============================================================================

/// Rewrites extracted instance-counter const-generics of an [`ItemTrait`]
/// into a single synthesized marker type-generic.
///
/// During extraction, [`CounterParams`] identifies which const-generics
/// participate in instance-counter generation. Those const-generics are
/// then removed from the trait signature and replaced with an internal
/// synthesized type parameter used by later proc-macro phases.
///
/// This transformation exists to avoid depending on unstable nightly
/// const-generic expression features such as `generic_const_exprs`.
/// Instead, later stages operate entirely through stable type-level
/// computation using re-exported utilities from `typenum` via `instances`
/// crate.
///
/// ## Generic Placement
///
/// The synthesized typenum marker is inserted at the generic position of
/// the first extracted counter generic.
///
/// This preserves the relative ordering of all remaining user-defined
/// generics and avoids introducing a new generic before existing
/// lifetime parameters.
///
/// Rust requires lifetime parameters to appear before type and const
/// parameters:
///
/// ```ignore
/// trait Example<'a, T> {}
/// ```
///
/// Therefore the transformation cannot simply prepend the synthesized
/// marker to the generic list.
///
/// Instead, all extracted counter generics are removed and a single
/// synthesized typenum marker is inserted at the position previously
/// occupied by the first counter generic.
///
/// Example:
///
/// ```ignore
/// #[trait_instance(2, 4)]
/// trait Example<'a, T, const A: u8, U, const B: u8> {}
/// ```
///
/// Extracted counters:
///
/// ```text
/// A
/// B
/// ```
///
/// Since `A` is the first extracted counter and occupies generic index
/// `2`, the generated marker is inserted at that same position:
///
/// ```ignore
/// trait Example<'a, T, __TypeNumCounters, U> {}
/// ```
///
/// This preserves:
///
/// - lifetime ordering requirements,
/// - user generic ordering,
/// - generic indices for non-counter parameters,
/// - and a deterministic location for generated typenum counters.
///
/// ## Example
///
/// Given:
///
/// ```ignore
/// #[trait_instance(0, 2)]
/// trait Example<const A: u8, const B: usize, const C: u8> {}
/// ```
///
/// extraction identifies:
///
/// ```text
/// A -> counter generic
/// C -> counter generic
/// ```
///
/// The transformation removes those counter generics and injects an
/// internal synthesized type parameter:
///
/// ```ignore
/// trait Example<__TypeNumCounters, const B: usize> {}
/// ```
///
/// Later phases use this synthesized generic to:
///
/// - perform stable type-level counter arithmetic,
/// - avoid unstable const-generic expression requirements,
/// - propagate instance-counter state through generated items,
/// - and drive typenum-based compile-time computation.
///
/// ## Generic Default Validation
///
/// After counter extraction and typenum-marker insertion, later phases
/// expect every remaining non-counter type and const generic to provide
/// a default value.
///
/// Example:
///
/// ```ignore
/// trait Example<
///     __TypeNumCounters,
///     T = (),
///     const N: usize = 0,
/// > {}
/// ```
///
/// This requirement allows implementation-side expansion to construct
/// deterministic trait paths without requiring arbitrary user-supplied
/// generic arguments.
///
/// The synthesized counter generic itself is excluded from this
/// requirement because its value is supplied by the generated typenum
/// counter tuple.
///
/// Lifetime parameters are also excluded because Rust does not permit
/// default lifetime parameters:
///
/// ```ignore
/// trait Example<'a, T = ()> {}
/// ```
///
/// Although lifetimes cannot declare defaults, later implementation-side
/// generic reconstruction may use `'static` as the effective fallback
/// lifetime when a fully specified trait path is required.
///
/// Consequently, after this transformation:
///
/// - counter generics are represented by `__TypeNumCounters`,
/// - remaining type generics must already define defaults,
/// - remaining const generics must already define defaults,
/// - lifetime generics are exempt from default validation,
/// - and proc-macro expansion can reconstruct deterministic trait
///   instantiations for metadata extraction and validation.
///
/// ## Hygeine
///
/// Since generated code relies on the `instances` crate,
/// proc-macro consumers are expected to use the proc-macros
/// re-exported by `instances` rather than depending on this
/// proc-macro crate directly.
///
/// The generated expansion references items provided by `instances`,
/// so using the re-exported macros ensures the required runtime
/// support types and traits are available automatically.
#[derive(Clone, Debug)]
pub(crate) struct InstanceTraitTypeNumCounters;

impl<'a> Transformation<ItemTrait, CounterParamsSlice<'a>> for InstanceTraitTypeNumCounters {
    fn raw_transform(
        &self,
        transform: &mut ItemTrait,
        context: &CounterParamsSlice<'a>,
    ) -> Result<(), TokenStream> {
        if context.len() > 4 {
            return Err(TypeNumErrors::Maximum4Counters {}.into());
        }
        let generics = &transform.generics.params;
        let mut rebuilt = Punctuated::<GenericParam, Comma>::new();

        let ident = gen_type_ident::<Self>();

        for (i, param) in generics.iter().enumerate() {
            let mut removed = false;

            for c in context.iter() {
                if c.generic_index >= generics.len() {
                    return Err(TypeNumCountersBugs::InvalidCounterParamIndex {}.into());
                }

                if c.generic_index == i {
                    removed = true;
                    break;
                }
            }

            if !removed {
                rebuilt.push(param.clone());
            }
        }

        let Some(first_counter) = context.first() else {
            return Err(TypeNumCountersBugs::CounterParamsAreEmpty {}.into());
        };

        let index = first_counter.generic_index;

        let item = GenericParam::Type(TypeParam {
            attrs: Vec::new(),
            ident,
            colon_token: None,
            bounds: Default::default(),
            eq_token: None,
            default: None,
        });

        let available_len = rebuilt.len();
        if index > available_len {
            return Err(TypeNumErrors::InvalidFirstCounter {
                param: first_counter.const_param.clone(),
                index,
                len: available_len,
            }
            .into());
        }

        rebuilt.insert(index, item);

        transform.generics.params = rebuilt;

        Ok(())
    }

    fn validate_transform(
        &self,
        transform: &ItemTrait,
        context: Option<&CounterParamsSlice<'a>>,
    ) -> Result<(), TokenStream> {
        let extracted;
        let counters = match context {
            Some(c) => c,
            None => {
                extracted = CounterParams::checked_extract(transform, &None)?;
                extracted.as_slice().as_ref().as_ref()
            }
        };

        let Some(first_counter) = counters.first() else {
            return Err(TypeNumCountersBugs::CounterParamsAreEmpty {}.into());
        };

        let params = &transform.generics.params;
        let index = first_counter.generic_index;
        let Some(param) = params.get(index) else {
            return Err(TypeNumCountersBugs::InvalidCounterParamIndex {}.into());
        };

        let GenericParam::Type(t) = param else {
            return Err(TypeNumCountersBugs::CounterParamNotTypeGeneric {}.into());
        };

        let ident = gen_type_ident::<Self>();

        if t.ident != ident {
            return Err(TypeNumCountersBugs::CounterTypeGenericInvalidIdent {}.into());
        }

        if !t.bounds.is_empty() {
            return Err(TypeNumCountersBugs::CounterTypeGenericHasBounds {}.into());
        }

        if t.default.is_some() {
            return Err(TypeNumCountersBugs::CounterTypeGenericHasDefault {}.into());
        }

        Ok(())
    }
}
