// SPDX-License-Identifier: MPL-2.0
//
// Part of Auguth Labs open-source softwares.
// Built for the Rust Programming Language Ecosystem.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2026 Auguth Labs (OPC) Pvt Ltd, India

// ===============================================================================
// ``````````````````````````````` GLOBAL ACCESSORS ``````````````````````````````
// ===============================================================================

//! Internal access traits used by the instances system to carry and recover
//! compile-time metadata across generated instance implementations.
//!
//! This module defines the type-level access interfaces used by the
//! [`crate`] re-exported proc-macros to communicate instance metadata through Rust's trait
//! system. The access traits identify generated instance metadata by
//! identifier hashes, contextual instance types, counter positions, and other
//! compile-time parameters, allowing later generated code to recover metadata
//! without revisiting the original instance definition.
//!
//! The access interfaces are implementation details of the instances macros
//! and are intended to be used only by generated code produced by those macros.
//! They are not intended for direct use by library users or by unrelated parts
//! of the crate.
//!
//! The traits are public only where required so that generated implementations
//! and generated access sites can cross the visibility boundaries imposed by
//! Rust's type system. Their public visibility should therefore not be
//! interpreted as a stable API guarantee.
//!
//! The signatures of these traits may change as the instances system evolves.
//! Code outside the generated instances machinery should not depend on their
//! names, generic parameter ordering, associated types, or other signature
//! details.
//!
//! The module currently provides access to:
//!
//! - `CounterAccess` - Complete counter tuple for an identified instance.
//! - `TerminalAccess` - Complete counter tuple for the terminal instance.
//! - `BoundaryAccess` - Boundary counter tuple and final identifier hash.
//! - `OnSetAccess` - Boundary counter tuple and initial identifier hash.
//! - `IdentHashLenAccess` - Identifier length associated with a counter generic position.
//!
//! All metadata exposed through these interfaces is resolved at compile time
//! through trait implementations generated by the instances macros.

// ===============================================================================
// ```````````````````````````````````` IMPORT ```````````````````````````````````
// ===============================================================================

// --- Local Crate Re-Exports ---
use crate::*;

// ===============================================================================
// ```````````````````````````````` COUNTER ACCESS ```````````````````````````````
// ===============================================================================

/// Resolves the counter tuple associated with an instance identified by one
/// compile-time identifier hash.
///
/// `A` is the `u64` const value produced by an identifier-hashing expression,
/// typically of the form `{ hash_ident(b"a-ident") }`. The hash identifies the
/// instance impl implemented towards `SelfTy`.
///
/// The associated `Counter` type is the complete typenum counter tuple
/// associated with the resolved instance. For a one-dimensional instance, the
/// tuple contains the counter for dimension `0`.
///
/// For example, an implementation may associate:
///
/// ```ignore
/// type Counter = (U2,);
/// ```
///
/// The counter can then be projected from the resolved tuple through
/// [`CountersGet<U0>`]:
///
/// ```ignore
/// <Global as CounterAccess1<{ hash_ident(b"foo") }, InstanceType>>::Counter
/// ```
///
/// resolves to `(U2,)`, whose `U0` element is `U2`.
pub trait CounterAccess1<const A: u64, SelfTy: ?Sized> {
    type Counter: CountersGet<U0>;
}

/// Resolves the counter tuple associated with an instance identified by a
/// two-element sequence of compile-time identifier hashes.
///
/// `A` and `B` are `u64` const values produced by identifier-hashing
/// expressions, typically of the form `{ hash_ident(b"ident") }`. Together
/// they preserve the ordered identifier sequence used to identify the
/// instance impl implemented towards `SelfTy`.
///
/// The associated `Counter` type is the complete typenum counter tuple
/// associated with the resolved instance. The tuple contains one counter for
/// each identifier dimension, with dimension `0` stored at `U0` and dimension
/// `1` stored at `U1`.
///
/// For example, an implementation may associate:
///
/// ```ignore
/// type Counter = (U0, U3);
/// ```
///
/// The tuple can then be queried independently at each dimension:
///
/// ```ignore
/// <Global as CounterAccess2<
///     { hash_ident(b"foo") },
///     { hash_ident(b"bar") },
///     InstanceType,
/// >>::Counter
/// ```
///
/// provides `U0` through [`CountersGet<U0>`] and `U3` through
/// [`CountersGet<U1>`].
pub trait CounterAccess2<const A: u64, const B: u64, SelfTy: ?Sized> {
    type Counter: CountersGet<U0> + CountersGet<U1>;
}

/// Resolves the counter tuple associated with an instance identified by a
/// three-element sequence of compile-time identifier hashes.
///
/// `A`, `B`, and `C` are `u64` const values produced by identifier-hashing
/// expressions, typically of the form `{ hash_ident(b"ident") }`. Their order
/// is the order of the identifiers used to identify the instance impl
/// implemented towards `SelfTy`.
///
/// The associated `Counter` type is the complete typenum counter tuple for
/// the resolved instance. Each tuple position corresponds to the same
/// dimension position in the identifier sequence.
///
/// For example:
///
/// ```text
/// identifier hashes:
///     A, B, C
///
/// counter tuple:
///     (U0, U1, U2)
/// ```
///
/// Each dimension is available through its corresponding [`CountersGet`]
/// implementation, allowing later type-level operations to select the
/// counter associated with an individual dimension.
pub trait CounterAccess3<const A: u64, const B: u64, const C: u64, SelfTy: ?Sized> {
    type Counter: CountersGet<U0> + CountersGet<U1> + CountersGet<U2>;
}

/// Resolves the counter tuple associated with an instance identified by a
/// four-element sequence of compile-time identifier hashes.
///
/// `A`, `B`, `C`, and `D` are `u64` const values produced by identifier-hashing
/// expressions, typically of the form `{ hash_ident(b"ident") }`. Their order
/// is the order of the identifiers used to identify the instance impl
/// implemented towards `SelfTy`.
///
/// The associated `Counter` type is the complete typenum counter tuple for
/// the resolved instance. Each tuple position corresponds to the same
/// dimension position in the identifier sequence.
///
/// For example:
///
/// ```text
/// identifier hashes:
///     A, B, C, D
///
/// counter tuple:
///     (U0, U1, U2, U3)
/// ```
///
/// Each dimension is available through its corresponding [`CountersGet`]
/// implementation, allowing later type-level operations to select an
/// individual counter from the resolved tuple.
pub trait CounterAccess4<const A: u64, const B: u64, const C: u64, const D: u64, SelfTy: ?Sized> {
    type Counter: CountersGet<U0> + CountersGet<U1> + CountersGet<U2> + CountersGet<U3>;
}

// ===============================================================================
// ``````````````````````````````` TERMINAL ACCESS ```````````````````````````````
// ===============================================================================

/// Resolves the counter tuple associated with the uniquely identified
/// terminal instance impl implemented towards `SelfTy`.
///
/// Unlike other access traits, `TerminalAccess` requires no identifier hash
/// sequence or counter-context generic arguments. The terminal instance is
/// unique for the contextual instance type, so `SelfTy` alone is sufficient
/// to select its generated access-trait implementation.
///
/// The associated `Terminal` type is the complete typenum counter tuple
/// associated with the resolved terminal instance. Its elements represent the
/// counters for the terminal instance's dimensions.
///
/// For example, a terminal access implementation may provide:
///
/// ```ignore
/// impl TerminalAccess<InstanceType> for Global {
///     type Terminal = (U2, U4);
/// }
/// ```
///
/// The counter tuple can then be recovered through the associated-type
/// projection:
///
/// ```ignore
/// <Global as TerminalAccess<InstanceType>>::Terminal
/// ```
///
/// `TerminalAccess` therefore provides a unique access path to the terminal
/// instance's complete counter context without requiring any identifier
/// sequence or explicit counter dimensions.
pub trait TerminalAccess<SelfTy: ?Sized> {
    type Terminal: Marker;
}

// ===============================================================================
// ``````````````````````````````` BOUNDARY ACCESS `````````````````````````````````
// ===============================================================================

/// Resolves the boundary counter tuple and the final identifier hash for the
/// root identifier sequence.
///
/// `BoundaryAccess0` is used when there is no preceding identifier sequence.
/// `SelfTy` alone therefore identifies the contextual instance whose
/// identifiers form the boundary.
///
/// `FINAL` is the hash of the final identifier occurring at this boundary.
///
/// For example, if the identifiers at the root boundary are:
///
/// ```text
/// a
/// b
/// c
///
/// FINAL = hash(c)
/// ```
///
/// The associated `Boundary` type is the complete typenum counter tuple for
/// the boundary and provides access to dimension `0` through
/// [`CountersGet<U0>`].
///
/// ```ignore
/// impl BoundaryAccess0<InstanceType> for Global {
///     const FINAL: u64 = { hash_ident(b"c") };
///     type Boundary = (U2,);
/// }
/// ```
///
/// The boundary information can then be recovered through:
///
/// ```ignore
/// <Global as BoundaryAccess0<InstanceType>>::FINAL
/// <Global as BoundaryAccess0<InstanceType>>::Boundary
/// ```
pub trait BoundaryAccess0<SelfTy: ?Sized> {
    const FINAL: u64;
    type Boundary: CountersGet<U0>;
}

/// Resolves the boundary counter tuple and the final identifier hash for a
/// boundary identified by one preceding compile-time identifier hash.
///
/// `A` is the `u64` const value produced by an identifier-hashing expression,
/// typically of the form `{ hash_ident(b"a-ident") }`. It identifies the
/// preceding identifier sequence whose immediate children form this boundary.
///
/// `FINAL` is the hash of the final identifier occurring immediately after
/// that preceding identifier sequence.
///
/// For example, given:
///
/// ```text
/// a, b
/// a, c
/// a, k
/// ```
///
/// the boundary identified by `a` has:
///
/// ```text
/// INITIAL = hash(b)
/// FINAL   = hash(k)
/// ```
///
/// `BoundaryAccess1` exposes the final hash and the complete counter tuple for
/// that boundary. The associated `Boundary` type provides access to dimensions
/// `0` and `1` through [`CountersGet`].
///
/// ```ignore
/// impl BoundaryAccess1<
///     { hash_ident(b"a") },
///     InstanceType,
/// > for Global {
///     const FINAL: u64 = { hash_ident(b"k") };
///     type Boundary = (U0, U3);
/// }
/// ```
pub trait BoundaryAccess1<const A: u64, SelfTy: ?Sized> {
    const FINAL: u64;
    type Boundary: CountersGet<U0> + CountersGet<U1>;
}

/// Resolves the boundary counter tuple and the final identifier hash for a
/// boundary identified by a two-element sequence of compile-time identifier
/// hashes.
///
/// `A` and `B` identify the preceding identifier sequence. The boundary
/// consists of the identifiers that immediately extend that sequence.
///
/// For example, given:
///
/// ```text
/// a, b, c
/// a, b, k
/// ```
///
/// the boundary identified by `a, b` has:
///
/// ```text
/// INITIAL = hash(c)
/// FINAL   = hash(k)
/// ```
///
/// `FINAL` therefore identifies the last identifier occurring at the boundary,
/// while the associated `Boundary` type contains the complete typenum counter
/// tuple for the `a, b` prefix.
///
/// Each tuple position corresponds to the same dimension position in the
/// preceding identifier sequence and can be accessed through the corresponding
/// [`CountersGet`] implementation.
pub trait BoundaryAccess2<const A: u64, const B: u64, SelfTy: ?Sized> {
    const FINAL: u64;
    type Boundary: CountersGet<U0> + CountersGet<U1> + CountersGet<U2>;
}

/// Resolves the boundary counter tuple and the final identifier hash for a
/// boundary identified by a three-element sequence of compile-time identifier
/// hashes.
///
/// `A`, `B`, and `C` identify the preceding identifier sequence. The boundary
/// consists of the identifiers that immediately extend that sequence.
///
/// For example, given:
///
/// ```text
/// a, b, c, d
/// a, b, c, k
/// ```
///
/// the boundary identified by `a, b, c` has:
///
/// ```text
/// INITIAL = hash(d)
/// FINAL   = hash(k)
/// ```
///
/// `FINAL` therefore identifies the last identifier occurring at the boundary,
/// while the associated `Boundary` type contains the complete typenum counter
/// tuple for the `a, b, c` prefix.
///
/// Each tuple position corresponds to the same dimension position in the
/// preceding identifier sequence and can be accessed through the corresponding
/// [`CountersGet`] implementation.
pub trait BoundaryAccess3<const A: u64, const B: u64, const C: u64, SelfTy: ?Sized> {
    const FINAL: u64;
    type Boundary: CountersGet<U0> + CountersGet<U1> + CountersGet<U2> + CountersGet<U3>;
}

// ===============================================================================
// `````````````````````````````` ON-SET ACCESS `````````````````````````````````
// ===============================================================================

/// Resolves the on-set counter tuple and the initial identifier hash for the
/// root identifier sequence.
///
/// `OnSetAccess0` is used when there is no preceding identifier sequence.
/// `SelfTy` alone therefore identifies the contextual instance whose
/// identifiers form the boundary.
///
/// `INITIAL` is the hash of the first identifier occurring at this boundary.
///
/// For example, if the identifiers at the root boundary are:
///
/// ```text
/// a
/// b
/// c
/// ```
///
/// then:
///
/// ```text
/// INITIAL = hash(a)
/// ```
///
/// The associated `OnSet` type is the complete typenum counter tuple for the
/// boundary and provides access to dimension `0` through
/// [`CountersGet<U0>`].
///
/// ```ignore
/// impl OnSetAccess0<InstanceType> for Global {
///     const INITIAL: u64 = { hash_ident(b"a") };
///     type OnSet = (U2,);
/// }
/// ```
pub trait OnSetAccess0<SelfTy: ?Sized> {
    const INITIAL: u64;
    type OnSet: CountersGet<U0>;
}

/// Resolves the on-set counter tuple and the initial identifier hash for a
/// boundary identified by one preceding compile-time identifier hash.
///
/// `A` identifies the preceding identifier sequence. `INITIAL` is the hash of
/// the first identifier occurring immediately after that sequence.
///
/// For example, given:
///
/// ```text
/// a, b
/// a, c
/// a, k
/// ```
///
/// the boundary identified by `a` has:
///
/// ```text
/// INITIAL = hash(b)
/// ```
///
/// The associated `OnSet` type is the complete typenum counter tuple for the
/// boundary. Its dimensions can be accessed through [`CountersGet`].
///
/// ```ignore
/// impl OnSetAccess1<
///     { hash_ident(b"a") },
///     InstanceType,
/// > for Global {
///     const INITIAL: u64 = { hash_ident(b"b") };
///     type OnSet = (U0, U3);
/// }
/// ```
pub trait OnSetAccess1<const A: u64, SelfTy: ?Sized> {
    const INITIAL: u64;
    type OnSet: CountersGet<U0> + CountersGet<U1>;
}

/// Resolves the on-set counter tuple and the initial identifier hash for a
/// boundary identified by a two-element sequence of compile-time identifier
/// hashes.
///
/// `A` and `B` identify the preceding identifier sequence. `INITIAL` is the
/// hash of the first identifier occurring immediately after that sequence.
///
/// For example, given:
///
/// ```text
/// a, b, c
/// a, b, k
/// ```
///
/// the boundary identified by `a, b` has:
///
/// ```text
/// INITIAL = hash(c)
/// ```
///
/// The associated `OnSet` type is the complete typenum counter tuple for the
/// `a, b` prefix. Each tuple position corresponds to the same dimension
/// position in the identifier sequence and can be accessed through the
/// corresponding [`CountersGet`] implementation.
pub trait OnSetAccess2<const A: u64, const B: u64, SelfTy: ?Sized> {
    const INITIAL: u64;
    type OnSet: CountersGet<U0> + CountersGet<U1> + CountersGet<U2>;
}

/// Resolves the on-set counter tuple and the initial identifier hash for a
/// boundary identified by a three-element sequence of compile-time identifier
/// hashes.
///
/// `A`, `B`, and `C` identify the preceding identifier sequence. `INITIAL`
/// is the hash of the first identifier occurring immediately after that
/// sequence.
///
/// For example, given:
///
/// ```text
/// a, b, c, d
/// a, b, c, k
/// ```
///
/// the boundary identified by `a, b, c` has:
///
/// ```text
/// INITIAL = hash(d)
/// ```
///
/// The associated `OnSet` type is the complete typenum counter tuple for the
/// `a, b, c` prefix. Each tuple position corresponds to the same dimension
/// position in the identifier sequence and can be accessed through the
/// corresponding [`CountersGet`] implementation.
pub trait OnSetAccess3<const A: u64, const B: u64, const C: u64, SelfTy: ?Sized> {
    const INITIAL: u64;
    type OnSet: CountersGet<U0> + CountersGet<U1> + CountersGet<U2> + CountersGet<U3>;
}

// ===============================================================================
// ```````````````````````````` HASH-LENGTH ACCESS ```````````````````````````````
// ===============================================================================

/// Resolves the identifier length associated with a counter generic position
/// within an instance identified by one compile-time identifier hash.
///
/// `A` is the `u64` const value produced by an identifier-hashing expression,
/// typically of the form `{ hash_ident(b"a-ident") }`. The hash identifies the
/// instance impl implemented towards `SelfTy`.
///
/// `GENERIC_IDX` selects the counter generic position whose corresponding
/// identifier length is being accessed.
///
/// The associated `Length` type is the typenum representation of the
/// identifier length at that generic position.
///
/// For example, given an instance identified by `A` with:
///
/// ```text
/// identifier:       a
/// generic index:    0
/// identifier length: 3
/// ```
///
/// the corresponding access may resolve as:
///
/// ```ignore
/// <Global as IdentHashLenAccess1<
///     { hash_ident(b"a") },
///     0,
///     InstanceType,
/// >>::Length
/// ```
///
/// and `Length` resolves to the typenum value representing `3`.
///
/// In most cases the length will be simply GENERIC_IDX + 1 in typenum.
pub trait IdentHashLenAccess1<const A: u64, const GENERIC_IDX: usize, SelfTy: ?Sized> {
    type Length: UnsignedTypeNum;
}

/// Resolves the identifier length associated with a counter generic position
/// within an instance identified by a two-element sequence of compile-time
/// identifier hashes.
///
/// `A` and `B` are `u64` const values produced by identifier-hashing
/// expressions, typically of the form `{ hash_ident(b"ident") }`. Together
/// they preserve the ordered identifier sequence used to identify the instance
/// impl implemented towards `SelfTy`.
///
/// `GENERIC_IDX` selects the counter generic position whose corresponding
/// identifier length is being accessed.
///
/// The associated `Length` type is the typenum representation of the
/// identifier length at the selected generic position.
///
/// For example, an instance identified by:
///
/// ```text
/// A, B
/// ```
///
/// may have identifier lengths:
///
/// ```text
/// generic index     identifier length
///       0                    3
///       1                    5
/// ```
///
/// The corresponding access:
///
/// ```ignore
/// <Global as IdentHashLenAccess2<
///     { hash_ident(b"a") },
///     { hash_ident(b"bbbbb") },
///     1,
///     InstanceType,
/// >>::Length
/// ```
///
/// resolves to the typenum value representing `5`.
///
/// In most cases the length will be simply GENERIC_IDX + 1 in typenum.
pub trait IdentHashLenAccess2<const A: u64, const B: u64, const GENERIC_IDX: usize, SelfTy: ?Sized>
{
    type Length: UnsignedTypeNum;
}

/// Resolves the identifier length associated with a counter generic position
/// within an instance identified by a three-element sequence of compile-time
/// identifier hashes.
///
/// `A`, `B`, and `C` are `u64` const values produced by identifier-hashing
/// expressions, typically of the form `{ hash_ident(b"ident") }`. Their order
/// is the order of the identifiers used to identify the instance impl
/// implemented towards `SelfTy`.
///
/// `GENERIC_IDX` selects the counter generic position whose corresponding
/// identifier length is being accessed.
///
/// The associated `Length` type is the typenum representation of the
/// identifier length at the selected generic position.
///
/// For example:
///
/// ```text
/// identifier path:
///     A, B, C
///
/// generic index:
///     0    1    2
///
/// identifier length:
///     3    5    7
/// ```
///
/// Selecting `GENERIC_IDX = 1` therefore resolves the identifier length
/// associated with the second generic position:
///
/// ```ignore
/// <Global as IdentHashLenAccess3<
///     HASH_A,
///     HASH_B,
///     HASH_C,
///     1,
///     InstanceType,
/// >>::Length
/// ```
///
/// The resolved `Length` is the typenum representation of `5`.
///
/// In most cases the length will be simply GENERIC_IDX + 1 in typenum.
pub trait IdentHashLenAccess3<
    const A: u64,
    const B: u64,
    const C: u64,
    const GENERIC_IDX: usize,
    SelfTy,
>
{
    type Length: UnsignedTypeNum;
}

/// Resolves the identifier length associated with a counter generic position
/// within an instance identified by a four-element sequence of compile-time
/// identifier hashes.
///
/// `A`, `B`, `C`, and `D` are `u64` const values produced by identifier-hashing
/// expressions, typically of the form `{ hash_ident(b"ident") }`. Their order
/// is the order of the identifiers used to identify the instance impl
/// implemented towards `SelfTy`.
///
/// `GENERIC_IDX` selects the counter generic position whose corresponding
/// identifier length is being accessed.
///
/// The associated `Length` type is the typenum representation of the
/// identifier length at the selected generic position.
///
/// For example:
///
/// ```text
/// identifier path:
///     A, B, C, D
///
/// generic index:
///     0    1    2    3
///
/// identifier length:
///     3    5    7    9
/// ```
///
/// Selecting `GENERIC_IDX = 2` resolves the identifier length associated with
/// the third generic position:
///
/// ```ignore
/// <Global as IdentHashLenAccess4<
///     HASH_A,
///     HASH_B,
///     HASH_C,
///     HASH_D,
///     2,
///     InstanceType,
/// >>::Length
/// ```
///
/// The resolved `Length` is the typenum representation of `7`.
///
/// In most cases the length will be simply GENERIC_IDX + 1 in typenum.
pub trait IdentHashLenAccess4<
    const A: u64,
    const B: u64,
    const C: u64,
    const D: u64,
    const GENERIC_IDX: usize,
    SelfTy,
>
{
    type Length: UnsignedTypeNum;
}
