// SPDX-License-Identifier: MPL-2.0
//
// Part of Auguth Labs open-source softwares.
// Built for the Rust Programming Language Ecosystem.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2026 Auguth Labs (OPC) Pvt Ltd, India

// ===============================================================================
// `````````````````````````````````` AFFILIATES `````````````````````````````````
// ===============================================================================

//! Internal type-level counter affiliation operations.
//!
//! This module contains the type-level operations used by the instances
//! macros to navigate and resolve positions within generated counter spaces.
//!
//! The traits and marker types defined here are implementation details of the
//! instances macros and should only be used by code generated by those macros.
//! They are not intended for direct use by users or by unrelated crate code.
//!
//! Their public visibility exists only to allow generated implementations and
//! generated access code to use these interfaces across the required Rust
//! visibility boundaries. Public visibility does not make these interfaces part
//! of the stable API.
//!
//! The signatures of these interfaces may therefore be changed freely as the
//! instances system evolves. Code outside the generated instances machinery
//! should not depend on their names, generic parameter ordering, associated
//! types, or other signature details.
//!
//! The module provides the following internal operations:
//!
//! - [`Affiliation`] - Identifies a type-level counter affiliation operation.
//! - [`DirectAffiliate`] - Resolves an affiliation directly from a complete counter tuple.
//! - `ReverseDispatch` - Performs dimension-by-dimension reverse traversal of a counter tuple.
//! - `CeilDispatch` - Resolves the ceil boundary through dimension-by-dimension dispatch.
//! - [`BackAffiliate`] - Resolves the final back-affiliate counter tuple from the current,
//!   reverse, reverse-next, and reverse-floor positions.
//! - [`CountersEqual`] - Compares corresponding positions of two counter tuples at the type level.
//!

// ===============================================================================
// ```````````````````````````````````` IMPORT ```````````````````````````````````
// ===============================================================================

// --- Local Crate Re-Exports ---
use crate::*;

// ===============================================================================
// ````````````````````````````````` AFFILIATIONS ````````````````````````````````
// ===============================================================================

/// Identifies a type-level counter affiliation operation.
///
/// An affiliation describes how a counter tuple is related to another
/// position in its counter space. Concrete affiliation marker types select the
/// operation performed by [`DirectAffiliate`].
pub trait Affiliation {}

/// Selects the preceding counter position.
///
/// `Reverse` moves a counter tuple to the immediately preceding valid
/// position, with higher dimensions preserved while lower dimensions are
/// traversed according to the reverse-dispatch rules.
pub struct Reverse;

/// Selects the immediately following counter position.
pub struct Next;

/// Selects the immediate preceding position within the current affiliation context.
pub struct Back;

/// Selects the floor boundary of an individual counter of the counter space.
pub struct Floor;

/// Selects the ceil boundary of the counter space.
pub struct Ceil;

impl Affiliation for Reverse {}
impl Affiliation for Next {}
impl Affiliation for Back {}
impl Affiliation for Floor {}
impl Affiliation for Ceil {}

// ===============================================================================
// ``````````````````````````````` DIRECT AFFILIATE ``````````````````````````````
// ===============================================================================

/// Resolves a direct affiliation of a counter tuple.
///
/// `Affiliate` specifies the affiliation operation to apply to the counter
/// tuple, while the associated `Output`] type represents the resulting
/// counter tuple.
///
/// Direct affiliation operates on the complete counter tuple as a single
/// type-level value. The concrete affiliation determines how that tuple is
/// transformed.
///
/// The [`Reverse`] affiliation resolves the preceding counter position,
/// while [`Ceil`] resolves the tuple at its ceil boundary.
///
/// `DirectAffiliate` therefore provides the common interface through which
/// higher-level type-level operations can request an affiliation without
/// directly depending on the dimensional dispatch implementation.
pub trait DirectAffiliate<Affiliate>
where
    Affiliate: Affiliation,
{
    type Output: Marker;
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// ``````````````````````````````` REVERSE DIRECTS ```````````````````````````````
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

impl<A> DirectAffiliate<Reverse> for (A,)
where
    A: Unsigned + IsEqual<U0>,
    <A as IsEqual<U0>>::Output: BoolTypeNum,
    (A,): ReverseDispatchA<<A as IsEqual<U0>>::Output>,
{
    type Output = <(A,) as ReverseDispatchA<<A as IsEqual<U0>>::Output>>::Output;
}

impl<A, B> DirectAffiliate<Reverse> for (A, B)
where
    A: Unsigned,
    B: Unsigned + IsEqual<U0>,
    <B as IsEqual<U0>>::Output: BoolTypeNum,
    (A, B): ReverseDispatchB<<B as IsEqual<U0>>::Output>,
{
    type Output = <(A, B) as ReverseDispatchB<<B as IsEqual<U0>>::Output>>::Output;
}

impl<A, B, C> DirectAffiliate<Reverse> for (A, B, C)
where
    A: Unsigned,
    B: Unsigned,
    C: Unsigned + IsEqual<U0>,
    <C as IsEqual<U0>>::Output: BoolTypeNum,
    (A, B, C): ReverseDispatchC<<C as IsEqual<U0>>::Output>,
{
    type Output = <(A, B, C) as ReverseDispatchC<<C as IsEqual<U0>>::Output>>::Output;
}

impl<A, B, C, D> DirectAffiliate<Reverse> for (A, B, C, D)
where
    A: Unsigned,
    B: Unsigned,
    C: Unsigned,
    D: Unsigned + IsEqual<U0>,
    <D as IsEqual<U0>>::Output: BoolTypeNum,
    (A, B, C, D): ReverseDispatchD<<D as IsEqual<U0>>::Output>,
{
    type Output = <(A, B, C, D) as ReverseDispatchD<<D as IsEqual<U0>>::Output>>::Output;
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// ````````````````````````````````` CEIL DIRECTS ````````````````````````````````
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

impl<A> DirectAffiliate<Ceil> for (A,)
where
    A: Unsigned + IsEqual<U0>,
    <A as IsEqual<U0>>::Output: BoolTypeNum,
    (A,): CeilDispatchA<<A as IsEqual<U0>>::Output>,
{
    type Output = <(A,) as CeilDispatchA<<A as IsEqual<U0>>::Output>>::Output;
}

impl<A, B> DirectAffiliate<Ceil> for (A, B)
where
    A: Unsigned,
    B: Unsigned + IsEqual<U0>,
    <B as IsEqual<U0>>::Output: BoolTypeNum,
    (A, B): CeilDispatchB<<B as IsEqual<U0>>::Output>,
{
    type Output = <(A, B) as CeilDispatchB<<B as IsEqual<U0>>::Output>>::Output;
}

impl<A, B, C> DirectAffiliate<Ceil> for (A, B, C)
where
    A: Unsigned,
    B: Unsigned,
    C: Unsigned + IsEqual<U0>,
    <C as IsEqual<U0>>::Output: BoolTypeNum,
    (A, B, C): CeilDispatchC<<C as IsEqual<U0>>::Output>,
{
    type Output = <(A, B, C) as CeilDispatchC<<C as IsEqual<U0>>::Output>>::Output;
}

impl<A, B, C, D> DirectAffiliate<Ceil> for (A, B, C, D)
where
    A: Unsigned,
    B: Unsigned,
    C: Unsigned,
    D: Unsigned + IsEqual<U0>,
    <D as IsEqual<U0>>::Output: BoolTypeNum,
    (A, B, C, D): CeilDispatchD<<D as IsEqual<U0>>::Output>,
{
    type Output = <(A, B, C, D) as CeilDispatchD<<D as IsEqual<U0>>::Output>>::Output;
}

// ===============================================================================
// `````````````````````````````` REVERSE AFFILIATE ``````````````````````````````
// ===============================================================================

/// Dispatches reverse-affiliate resolution from the most significant
/// counter dimension `D`.
///
/// `D` is the highest-order dimension in a four-counter tuple
/// `(A, B, C, D)`. The `IsZero` parameter selects whether that dimension
/// has reached zero.
///
/// When `D` is non-zero, the default reverse-affiliate step decrements `D`
/// while preserving all lower dimensions.
///
/// When `D` is zero, the zero-state implementation delegates resolution to
/// [`ReverseDispatchC`], making `C` the next most significant dimension that
/// can be decremented.
///
/// The zero-state implementation therefore acts as the recursive boundary
/// between dimensions: a dimension is exhausted before reverse resolution
/// proceeds to the next lower dimension.
pub trait ReverseDispatchD<IsZero: BoolTypeNum> {
    type Output: Marker;
}

/// Dispatches reverse-affiliate resolution from the most significant
/// remaining counter dimension `C`.
///
/// `C` is the highest-order dimension considered after `D` has reached zero
/// in a four-counter tuple, or the highest-order dimension in a three-counter
/// tuple `(A, B, C)`. The `IsZero` parameter selects whether `C` has reached
/// zero.
///
/// When `C` is non-zero, the default reverse-affiliate step decrements `C`
/// while preserving all lower dimensions.
///
/// When `C` is zero, the zero-state implementation delegates resolution to
/// [`ReverseDispatchB`], making `B` the next most significant dimension that
/// can be decremented.
///
/// Thus, the zero-state implementation is not itself a terminal case unless
/// `B` is also exhausted. It transfers reverse resolution to the next
/// dimension in significance order.
pub trait ReverseDispatchC<IsZero: BoolTypeNum> {
    type Output: Marker;
}

/// Dispatches reverse-affiliate resolution from the most significant
/// remaining counter dimension `B`.
///
/// `B` is the highest-order dimension considered after all higher dimensions
/// have reached zero, or the highest-order dimension in a two-counter tuple
/// `(A, B)`. The `IsZero` parameter selects whether `B` has reached zero.
///
/// When `B` is non-zero, the default reverse-affiliate step decrements `B`
/// while preserving the lower dimension `A`.
///
/// When `B` is zero, the zero-state implementation delegates resolution to
/// [`ReverseDispatchA`], making `A` the final dimension available for reverse
/// decrement.
///
/// This establishes the recursive progression from higher-significance
/// dimensions toward the least significant dimension.
pub trait ReverseDispatchB<IsZero: BoolTypeNum> {
    type Output: Marker;
}

/// Dispatches reverse-affiliate resolution for the least significant
/// remaining counter dimension `A`.
///
/// `A` is the final dimension reached after every more significant dimension
/// has been exhausted. The `IsZero` parameter selects whether `A` has reached
/// zero.
///
/// When `A` is non-zero, the default reverse-affiliate step decrements `A`.
///
/// When `A` is zero, the zero-state implementation is the terminal default:
/// no further reverse-affiliate step is possible, so the counter tuple is
/// returned unchanged.
///
/// `ReverseDispatchA` therefore provides the termination point of the
/// dimension-by-dimension reverse traversal.
pub trait ReverseDispatchA<IsZero: BoolTypeNum> {
    type Output: Marker;
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// `````````````````````````````````` 1 COUNTER ``````````````````````````````````
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// if A != 0 in (A) => (A-1)
impl<A> ReverseDispatchA<B0> for (A,)
where
    A: Unsigned + Sub<U1>,
    Diff<A, U1>: Unsigned,
    (Diff<A, U1>,): Marker,
{
    type Output = (Diff<A, U1>,);
}

// if ALL ZERO (0) => unchanged
impl ReverseDispatchA<B1> for (U0,) {
    type Output = (U0,);
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// `````````````````````````````````` 2 COUNTERS `````````````````````````````````
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// if B != 0 in (A,B) => (A,B-1)
impl<A, B> ReverseDispatchB<B0> for (A, B)
where
    A: Unsigned,
    B: Unsigned + Sub<U1>,
    Diff<B, U1>: Unsigned,
    (A, Diff<B, U1>): Marker,
{
    type Output = (A, Diff<B, U1>);
}

// if B == 0 => recurse into A
impl<A> ReverseDispatchB<B1> for (A, U0)
where
    A: Unsigned + IsEqual<U0>,
    <A as IsEqual<U0>>::Output: BoolTypeNum,
    (A, U0): ReverseDispatchA<<A as IsEqual<U0>>::Output>,
{
    type Output = <(A, U0) as ReverseDispatchA<<A as IsEqual<U0>>::Output>>::Output;
}

// if A != 0 in (A,0) => (A-1,0)
impl<A> ReverseDispatchA<B0> for (A, U0)
where
    A: Unsigned + Sub<U1>,
    Diff<A, U1>: Unsigned,
    (Diff<A, U1>, U0): Marker,
{
    type Output = (Diff<A, U1>, U0);
}

// if ALL ZERO (0,0,0) => unchanged
impl ReverseDispatchA<B1> for (U0, U0) {
    type Output = (U0, U0);
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// `````````````````````````````````` 3 COUNTERS `````````````````````````````````
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// if C != 0 in (A,B,C) => (A,B,C-1)
impl<A, B, C> ReverseDispatchC<B0> for (A, B, C)
where
    A: Unsigned,
    B: Unsigned,
    C: Unsigned + Sub<U1>,
    Diff<C, U1>: Unsigned,
    (A, B, Diff<C, U1>): Marker,
{
    type Output = (A, B, Diff<C, U1>);
}

// if C == 0 => recurse into B
impl<A, B> ReverseDispatchC<B1> for (A, B, U0)
where
    A: Unsigned,
    B: Unsigned + IsEqual<U0>,
    <B as IsEqual<U0>>::Output: BoolTypeNum,
    (A, B, U0): ReverseDispatchB<<B as IsEqual<U0>>::Output>,
    <(A, B, U0) as ReverseDispatchB<<B as IsEqual<U0>>::Output>>::Output: Marker,
{
    type Output = <(A, B, U0) as ReverseDispatchB<<B as IsEqual<U0>>::Output>>::Output;
}

// if B != 0 in (A,B,0) => (A,B-1,0)
impl<A, B> ReverseDispatchB<B0> for (A, B, U0)
where
    A: Unsigned,
    B: Unsigned + Sub<U1>,
    Diff<B, U1>: Unsigned,
    (A, Diff<B, U1>, U0): Marker,
{
    type Output = (A, Diff<B, U1>, U0);
}

// if B == 0 => recurse into A
impl<A> ReverseDispatchB<B1> for (A, U0, U0)
where
    A: Unsigned + IsEqual<U0>,
    <A as IsEqual<U0>>::Output: BoolTypeNum,
    (A, U0, U0): ReverseDispatchA<<A as IsEqual<U0>>::Output>,
{
    type Output = <(A, U0, U0) as ReverseDispatchA<<A as IsEqual<U0>>::Output>>::Output;
}

// if A != 0 in (A,0,0) => (A-1,0,0)
impl<A> ReverseDispatchA<B0> for (A, U0, U0)
where
    A: Unsigned + Sub<U1>,
    Diff<A, U1>: Unsigned,
    (Diff<A, U1>, U0, U0): Marker,
{
    type Output = (Diff<A, U1>, U0, U0);
}

// if ALL ZERO (0,0,0) => unchanged
impl ReverseDispatchA<B1> for (U0, U0, U0) {
    type Output = (U0, U0, U0);
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// `````````````````````````````````` 4 COUNTERS `````````````````````````````````
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// if D != 0 in (A,B,C,D) => (A,B,C,D-1)
impl<A, B, C, D> ReverseDispatchD<B0> for (A, B, C, D)
where
    A: Unsigned,
    B: Unsigned,
    C: Unsigned,
    D: Unsigned + Sub<U1>,
    Diff<D, U1>: Unsigned,
    (A, B, C, Diff<D, U1>): Marker,
{
    type Output = (A, B, C, Diff<D, U1>);
}

// if D == 0 => recurse into C
impl<A, B, C> ReverseDispatchD<B1> for (A, B, C, U0)
where
    A: Unsigned,
    B: Unsigned,
    C: Unsigned + IsEqual<U0>,
    <C as IsEqual<U0>>::Output: BoolTypeNum,
    (A, B, C, U0): ReverseDispatchC<<C as IsEqual<U0>>::Output>,
    <(A, B, C, U0) as ReverseDispatchC<<C as IsEqual<U0>>::Output>>::Output: Marker,
{
    type Output = <(A, B, C, U0) as ReverseDispatchC<<C as IsEqual<U0>>::Output>>::Output;
}

// if C != 0 in (A,B,C,0) => (A,B,C-1,0)
impl<A, B, C> ReverseDispatchC<B0> for (A, B, C, U0)
where
    A: Unsigned,
    B: Unsigned,
    C: Unsigned + Sub<U1>,
    Diff<C, U1>: Unsigned,
    (A, B, Diff<C, U1>, U0): Marker,
{
    type Output = (A, B, Diff<C, U1>, U0);
}

// if C == 0 => recurse into B
impl<A, B> ReverseDispatchC<B1> for (A, B, U0, U0)
where
    A: Unsigned,
    B: Unsigned + IsEqual<U0>,
    <B as IsEqual<U0>>::Output: BoolTypeNum,
    (A, B, U0, U0): ReverseDispatchB<<B as IsEqual<U0>>::Output>,
    <(A, B, U0, U0) as ReverseDispatchB<<B as IsEqual<U0>>::Output>>::Output: Marker,
{
    type Output = <(A, B, U0, U0) as ReverseDispatchB<<B as IsEqual<U0>>::Output>>::Output;
}

// if B != 0 in (A,B,0,0) => (A,B-1,0,0)
impl<A, B> ReverseDispatchB<B0> for (A, B, U0, U0)
where
    A: Unsigned,
    B: Unsigned + Sub<U1>,
    Diff<B, U1>: Unsigned,
    (A, Diff<B, U1>, U0, U0): Marker,
{
    type Output = (A, Diff<B, U1>, U0, U0);
}

// if B == 0 => recurse into A
impl<A> ReverseDispatchB<B1> for (A, U0, U0, U0)
where
    A: Unsigned + IsEqual<U0>,
    <A as IsEqual<U0>>::Output: BoolTypeNum,
    (A, U0, U0, U0): ReverseDispatchA<<A as IsEqual<U0>>::Output>,
{
    type Output = <(A, U0, U0, U0) as ReverseDispatchA<<A as IsEqual<U0>>::Output>>::Output;
}

// if A != 0 in (A,0,0,0) => (A-1,0,0,0)
impl<A> ReverseDispatchA<B0> for (A, U0, U0, U0)
where
    A: Unsigned + Sub<U1>,
    Diff<A, U1>: Unsigned,
    (Diff<A, U1>, U0, U0, U0): Marker,
{
    type Output = (Diff<A, U1>, U0, U0, U0);
}

// if ALL ZERO (0,0,0,0) => unchanged
impl ReverseDispatchA<B1> for (U0, U0, U0, U0) {
    type Output = (U0, U0, U0, U0);
}

// ===============================================================================
// ```````````````````````````````` CEIL AFFILIATE ```````````````````````````````
// ===============================================================================

/// Dispatches ceil resolution from the most significant counter dimension
/// `D`.
///
/// `D` is the highest-order dimension in a four-counter tuple
/// `(A, B, C, D)`. The `IsZero` parameter determines whether `D` has reached
/// zero.
///
/// When `D` is non-zero, the default implementation resolves the ceil value
/// by setting `D` to zero while preserving all lower dimensions.
///
/// When `D` is zero, the zero-state implementation delegates to
/// [`CeilDispatchC`], making `C` the next most significant dimension that can
/// be resolved.
///
/// The zero-state implementation therefore represents a dimension boundary:
/// the current dimension has already reached its ceil boundary, so resolution
/// continues with the next lower dimension.
///
/// The same dispatch trait is used for tuples with fewer counters by treating
/// the highest available dimension as the current most significant dimension.
///
/// ```text
/// (A, B, C, D)
///          D   current most significant dimension
///          C
///          B
///          A
/// ```
pub trait CeilDispatchD<IsZero: BoolTypeNum> {
    type Output: Marker;
}

/// Dispatches ceil resolution from the most significant remaining counter
/// dimension `C`.
///
/// `C` is the highest-order dimension considered after `D` has reached zero
/// in a four-counter tuple, and is the highest-order dimension of a
/// three-counter tuple `(A, B, C)`.
///
/// When `C` is non-zero, the default implementation resolves the ceil value
/// by setting `C` to zero while preserving all lower dimensions.
///
/// When `C` is zero, the zero-state implementation delegates to
/// [`CeilDispatchB`], making `B` the next most significant dimension that can
/// be resolved.
///
/// Thus, the [`B0`] implementation performs the ceil operation at the current
/// dimension, while the [`B1`] implementation transfers resolution to the next
/// lower dimension.
///
/// ```text
/// (A, B, C)
///       C   current most significant dimension
///       B
///       A
/// ```
pub trait CeilDispatchC<IsZero: BoolTypeNum> {
    type Output: Marker;
}

/// Dispatches ceil resolution from the most significant remaining counter
/// dimension `B`.
///
/// `B` is the highest-order dimension considered after all higher dimensions
/// have reached zero, and is the highest-order dimension of a two-counter
/// tuple `(A, B)`.
///
/// When `B` is non-zero, the default implementation resolves the ceil value
/// by setting `B` to zero while preserving the lower dimension `A`.
///
/// When `B` is zero, the zero-state implementation delegates to
/// [`CeilDispatchA`], making `A` the final dimension available for ceil
/// resolution.
///
/// This establishes the recursive progression from higher-significance
/// dimensions toward the least significant dimension.
///
/// ```text
/// (A, B)
///    B   current most significant dimension
///    A
/// ```
pub trait CeilDispatchB<IsZero: BoolTypeNum> {
    type Output: Marker;
}

/// Dispatches ceil resolution for the least significant remaining counter
/// dimension `A`.
///
/// `A` is the final dimension reached after every more significant dimension
/// has reached zero.
///
/// When `A` is non-zero, the default implementation resolves the ceil value
/// by setting `A` to zero.
///
/// When `A` is already zero, the zero-state implementation is the terminal
/// default. No further dimension remains to resolve, so the tuple is returned
/// unchanged.
///
/// `CeilDispatchA` therefore provides the termination point of the
/// dimension-by-dimension ceil traversal.
///
/// ```text
/// (A)
///  A   final remaining dimension
/// ```
///
/// For the all-zero tuple, the existing zero state is already the ceil state,
/// so the terminal implementation preserves it unchanged.
pub trait CeilDispatchA<IsZero: BoolTypeNum> {
    type Output: Marker;
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// `````````````````````````````` 1 COUNTER ````````````````````````````````````
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// if A != 0 in (A) => (0)
impl<A> CeilDispatchA<B0> for (A,)
where
    A: Unsigned,
{
    type Output = (U0,);
}

// if ALL ZERO => unchanged
impl CeilDispatchA<B1> for (U0,) {
    type Output = (U0,);
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// `````````````````````````````` 2 COUNTERS ````````````````````````````````````
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// if B != 0 in (A,B) => (A,0)
impl<A, B> CeilDispatchB<B0> for (A, B)
where
    A: Unsigned,
    B: Unsigned,
    (A, U0): Marker,
{
    type Output = (A, U0);
}

// if B == 0 => recurse into A
impl<A> CeilDispatchB<B1> for (A, U0)
where
    A: Unsigned + IsEqual<U0>,
    <A as IsEqual<U0>>::Output: BoolTypeNum,
    (A, U0): CeilDispatchA<<A as IsEqual<U0>>::Output>,
{
    type Output = <(A, U0) as CeilDispatchA<<A as IsEqual<U0>>::Output>>::Output;
}

// if A != 0 in (A,0) => (0,0)
impl<A> CeilDispatchA<B0> for (A, U0)
where
    A: Unsigned,
{
    type Output = (U0, U0);
}

// if ALL ZERO => unchanged
impl CeilDispatchA<B1> for (U0, U0) {
    type Output = (U0, U0);
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// `````````````````````````````` 3 COUNTERS ````````````````````````````````````
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// if C != 0 in (A,B,C) => (A,B,0)
impl<A, B, C> CeilDispatchC<B0> for (A, B, C)
where
    A: Unsigned,
    B: Unsigned,
    C: Unsigned,
    (A, B, U0): Marker,
{
    type Output = (A, B, U0);
}

// if C == 0 => recurse into B
impl<A, B> CeilDispatchC<B1> for (A, B, U0)
where
    A: Unsigned,
    B: Unsigned + IsEqual<U0>,
    <B as IsEqual<U0>>::Output: BoolTypeNum,
    (A, B, U0): CeilDispatchB<<B as IsEqual<U0>>::Output>,
{
    type Output = <(A, B, U0) as CeilDispatchB<<B as IsEqual<U0>>::Output>>::Output;
}

// if B != 0 in (A,B,0) => (A,0,0)
impl<A, B> CeilDispatchB<B0> for (A, B, U0)
where
    A: Unsigned,
    B: Unsigned,
    (A, U0, U0): Marker,
{
    type Output = (A, U0, U0);
}

// if B == 0 => recurse into A
impl<A> CeilDispatchB<B1> for (A, U0, U0)
where
    A: Unsigned + IsEqual<U0>,
    <A as IsEqual<U0>>::Output: BoolTypeNum,
    (A, U0, U0): CeilDispatchA<<A as IsEqual<U0>>::Output>,
{
    type Output = <(A, U0, U0) as CeilDispatchA<<A as IsEqual<U0>>::Output>>::Output;
}

// if A != 0 in (A,0,0) => (0,0,0)
impl<A> CeilDispatchA<B0> for (A, U0, U0)
where
    A: Unsigned,
{
    type Output = (U0, U0, U0);
}

// if ALL ZERO => unchanged
impl CeilDispatchA<B1> for (U0, U0, U0) {
    type Output = (U0, U0, U0);
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// `````````````````````````````` 4 COUNTERS ````````````````````````````````````
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// if D != 0 in (A,B,C,D) => (A,B,C,0)
impl<A, B, C, D> CeilDispatchD<B0> for (A, B, C, D)
where
    A: Unsigned,
    B: Unsigned,
    C: Unsigned,
    D: Unsigned,
    (A, B, C, U0): Marker,
{
    type Output = (A, B, C, U0);
}

// if D == 0 => recurse into C
impl<A, B, C> CeilDispatchD<B1> for (A, B, C, U0)
where
    A: Unsigned,
    B: Unsigned,
    C: Unsigned + IsEqual<U0>,
    <C as IsEqual<U0>>::Output: BoolTypeNum,
    (A, B, C, U0): CeilDispatchC<<C as IsEqual<U0>>::Output>,
{
    type Output = <(A, B, C, U0) as CeilDispatchC<<C as IsEqual<U0>>::Output>>::Output;
}

// if C != 0 in (A,B,C,0) => (A,B,0,0)
impl<A, B, C> CeilDispatchC<B0> for (A, B, C, U0)
where
    A: Unsigned,
    B: Unsigned,
    C: Unsigned,
    (A, B, U0, U0): Marker,
{
    type Output = (A, B, U0, U0);
}

// if C == 0 => recurse into B
impl<A, B> CeilDispatchC<B1> for (A, B, U0, U0)
where
    A: Unsigned,
    B: Unsigned + IsEqual<U0>,
    <B as IsEqual<U0>>::Output: BoolTypeNum,
    (A, B, U0, U0): CeilDispatchB<<B as IsEqual<U0>>::Output>,
{
    type Output = <(A, B, U0, U0) as CeilDispatchB<<B as IsEqual<U0>>::Output>>::Output;
}

// if B != 0 in (A,B,0,0) => (A,0,0,0)
impl<A, B> CeilDispatchB<B0> for (A, B, U0, U0)
where
    A: Unsigned,
    B: Unsigned,
    (A, U0, U0, U0): Marker,
{
    type Output = (A, U0, U0, U0);
}

// if B == 0 => recurse into A
impl<A> CeilDispatchB<B1> for (A, U0, U0, U0)
where
    A: Unsigned + IsEqual<U0>,
    <A as IsEqual<U0>>::Output: BoolTypeNum,
    (A, U0, U0, U0): CeilDispatchA<<A as IsEqual<U0>>::Output>,
{
    type Output = <(A, U0, U0, U0) as CeilDispatchA<<A as IsEqual<U0>>::Output>>::Output;
}

// if A != 0 in (A,0,0,0) => (0,0,0,0)
impl<A> CeilDispatchA<B0> for (A, U0, U0, U0)
where
    A: Unsigned,
{
    type Output = (U0, U0, U0, U0);
}

// if ALL ZERO => unchanged
impl CeilDispatchA<B1> for (U0, U0, U0, U0) {
    type Output = (U0, U0, U0, U0);
}

// ===========================================================================
// `````````````````````````` BACK AFFILIATE ````````````````````````````````
// ===========================================================================

/// Resolves the back-affiliate counter tuple.
///
/// The resolution is performed in two stages. First, `Current` is checked
/// against the global minimum. If it is the global minimum, no back-affiliate
/// exists and `Current` is retained.
///
/// Otherwise, `ReverseNext` is compared with `Current`. When they are equal,
/// `Reverse` is selected; otherwise `ReverseFloor` is selected.
///
/// Inputs:
///
/// ```text
/// Current
/// Reverse
/// ReverseNext
/// ReverseFloor
/// ```
///
/// Resolution:
///
/// ```text
/// Current == GlobalMin
///     => Current
///
/// Current != GlobalMin
///     => ReverseNext == Current
///
/// ReverseNext == Current
///     => Reverse
///
/// ReverseNext != Current
///     => ReverseFloor
/// ```
///
/// The associated `Output` type is therefore the counter tuple determined
/// by these two compile-time decisions.
pub trait BackAffiliate<Reverse, ReverseNext, ReverseFloor, IsGlobalMin>
where
    Reverse: Marker,
    ReverseNext: Marker,
    ReverseFloor: Marker,
    IsGlobalMin: BoolTypeNum,
{
    type Output: Marker;
}

/// Dispatches back-affiliate resolution according to whether `Current` is
/// the global minimum.
///
/// When `IsGlobalMin` is true, the global-minimum case is terminal and
/// `Current` is returned unchanged.
///
/// When `IsGlobalMin` is false, the resolution continues to
/// [`BackAffiliateEqualityDispatch`], which determines whether `Reverse` or
/// `ReverseFloor` is the appropriate result.
pub trait BackAffiliateGlobalMinDispatch<Reverse, ReverseNext, ReverseFloor, IsGlobalMin>
where
    Reverse: Marker,
    ReverseNext: Marker,
    ReverseFloor: Marker,
    IsGlobalMin: BoolTypeNum,
{
    type Output: Marker;
}

/// Dispatches back-affiliate resolution according to whether `ReverseNext`
/// is equal to `Current`.
///
/// This dispatch is reached only after `Current` has been determined not to
/// be the global minimum.
///
/// When `CountersEqual` is true, `ReverseNext` identifies the current
/// position's reverse successor, so `Reverse` is selected.
///
/// When `CountersEqual` is false, `ReverseNext` does not equal `Current`, so
/// the back-affiliate resolves to `ReverseFloor`.
pub trait BackAffiliateEqualityDispatch<Reverse, ReverseFloor, CountersEqual>
where
    Reverse: Marker,
    ReverseFloor: Marker,
    CountersEqual: BoolTypeNum,
{
    type Output: Marker;
}

/// Global-minimum case.
///
/// ```text
/// if Current == GlobalMin => Current
/// ```
///
/// The current counter tuple is already at the global minimum, so no further
/// back-affiliate resolution is performed.
impl<Current, Reverse, ReverseNext, ReverseFloor>
    BackAffiliateGlobalMinDispatch<Reverse, ReverseNext, ReverseFloor, B1> for Current
where
    Current: Marker,
    Reverse: Marker,
    ReverseNext: Marker,
    ReverseFloor: Marker,
{
    type Output = Current;
}

/// Non-global-minimum case.
///
/// ```text
/// if Current != GlobalMin => evaluate equality dispatch
/// ```
///
/// The current counter tuple is not at the global minimum, so resolution
/// continues by comparing `Current` with `ReverseNext`.
impl<Current, Reverse, ReverseNext, ReverseFloor>
    BackAffiliateGlobalMinDispatch<Reverse, ReverseNext, ReverseFloor, B0> for Current
where
    Current: CountersEqual<ReverseNext>,
    Current: BackAffiliateEqualityDispatch<
            Reverse,
            ReverseFloor,
            <Current as CountersEqual<ReverseNext>>::Output,
        >,
    Current: Marker,
    Reverse: Marker,
    ReverseNext: Marker,
    ReverseFloor: Marker,
    <Current as CountersEqual<ReverseNext>>::Output: BoolTypeNum,
{
    type Output = <Current as BackAffiliateEqualityDispatch<
        Reverse,
        ReverseFloor,
        <Current as CountersEqual<ReverseNext>>::Output,
    >>::Output;
}

/// Equality case.
///
/// ```text
/// if ReverseNext == Current => Reverse
/// ```
///
/// `ReverseNext` is equal to `Current`, so `Reverse` is the resolved
/// back-affiliate counter tuple.
impl<Current, Reverse, ReverseFloor> BackAffiliateEqualityDispatch<Reverse, ReverseFloor, B1>
    for Current
where
    Current: Marker,
    Reverse: Marker,
    ReverseFloor: Marker,
{
    type Output = Reverse;
}

/// Inequality case.
///
/// ```text
/// if ReverseNext != Current => ReverseFloor
/// ```
///
/// `ReverseNext` is not equal to `Current`, so the back-affiliate resolves to
/// `ReverseFloor`.
impl<Current, Reverse, ReverseFloor> BackAffiliateEqualityDispatch<Reverse, ReverseFloor, B0>
    for Current
where
    Current: Marker,
    Reverse: Marker,
    ReverseFloor: Marker,
{
    type Output = ReverseFloor;
}

/// Entry point for back-affiliate resolution.
///
/// The resolution first determines whether `Current` is the global minimum.
/// If it is, `Current` is returned unchanged.
///
/// Otherwise, `Current` is compared with `ReverseNext`. When they are equal,
/// `Reverse` is selected; when they differ, `ReverseFloor` is selected.
///
/// Example:
///
/// ```text
/// Current      = (U0, U0, U5)
/// Reverse      = (U0, U0, U4)
/// ReverseNext  = (U0, U0, U5)
/// ReverseFloor = (U0, U0, U0)
///
/// Current != GlobalMin
/// ReverseNext == Current
///
/// Output = Reverse
/// ```
///
/// Example:
///
/// ```text
/// Current      = (U0, U0, U7)
/// Reverse      = (U0, U0, U6)
/// ReverseNext  = (U0, U0, U9)
/// ReverseFloor = (U0, U0, U0)
///
/// Current != GlobalMin
/// ReverseNext != Current
///
/// Output = ReverseFloor
/// ```
///
/// Example:
///
/// ```text
/// Current = GlobalMin
///
/// Output = Current
/// ```
///
/// `BackAffiliate` provides the public entry point while
/// [`BackAffiliateGlobalMinDispatch`] and
/// [`BackAffiliateEqualityDispatch`] perform the individual compile-time
/// decisions.
impl<Current, Reverse, ReverseNext, ReverseFloor, IsGlobalMin>
    BackAffiliate<Reverse, ReverseNext, ReverseFloor, IsGlobalMin> for Current
where
    Current: BackAffiliateGlobalMinDispatch<Reverse, ReverseNext, ReverseFloor, IsGlobalMin>,
    Current: Marker,
    Reverse: Marker,
    ReverseNext: Marker,
    ReverseFloor: Marker,
    IsGlobalMin: BoolTypeNum,
{
    type Output = <Current as BackAffiliateGlobalMinDispatch<
        Reverse,
        ReverseNext,
        ReverseFloor,
        IsGlobalMin,
    >>::Output;
}

// ===========================================================================
// ```````````````````````````` COUNTERS EQ ``````````````````````````````````
// ===========================================================================

/// Compares two counter tuples element by element.
///
/// The associated `Output` is [`B1`] when every corresponding counter is
/// equal, and [`B0`] when at least one counter differs.
///
/// Each counter position is compared independently with [`IsEqual`], and the
/// resulting boolean values are combined with [`BitAnd`].
pub trait CountersEqual<Rhs: Marker> {
    type Output: BoolTypeNum;
}

/// Equality result for the first counter dimension.
///
/// `EqA0` represents the equality result of the first corresponding counter.
type EqA0<A0, B0> = <A0 as IsEqual<B0>>::Output;

/// Compares two single-counter tuples element by element.
///
/// The corresponding counter pairs are compared:
///
/// ```text
/// (A0)
/// (B0)
/// ```
///
/// Their equality result is:
///
/// ```text
/// A0 == B0
/// ```
///
/// The resulting `Output` is [`B1`] when the two counter positions are equal,
/// and [`B0`] when they differ.
impl<A0, B0> CountersEqual<(B0,)> for (A0,)
where
    A0: IsEqual<B0>,
    EqA0<A0, B0>: BoolTypeNum,
    (B0,): Marker,
{
    type Output = EqA0<A0, B0>;
}

/// Equality result for the first two counter dimensions.
///
/// `EqA1` combines the equality results of the first two corresponding
/// counters into a single type-level boolean.
type EqA1<A0, A1, B0, B1> =
    <<A0 as IsEqual<B0>>::Output as BitAnd<<A1 as IsEqual<B1>>::Output>>::Output;

/// Compares two two-counter tuples element by element.
///
/// The corresponding counter pairs are compared:
///
/// ```text
/// (A0, A1)
/// (B0, B1)
/// ```
///
/// Their equality results are combined with `BitAnd`:
///
/// ```text
/// A0 == B0
/// A1 == B1
///
/// (A0 == B0) AND (A1 == B1)
/// ```
///
/// The resulting `Output` is [`B1`] only when both counter positions are
/// equal. If any corresponding counter differs, the result is [`B0`].
impl<A0, A1, B0, B1> CountersEqual<(B0, B1)> for (A0, A1)
where
    A0: IsEqual<B0>,
    A1: IsEqual<B1>,
    <A0 as IsEqual<B0>>::Output: BitAnd<<A1 as IsEqual<B1>>::Output>,
    EqA1<A0, A1, B0, B1>: BoolTypeNum,
    (B0, B1): Marker,
{
    type Output = EqA1<A0, A1, B0, B1>;
}

/// Equality result for the first three counter dimensions.
///
/// `EqA2` combines the equality results of the first three corresponding
/// counters into a single type-level boolean.
type EqA2<A0, A1, A2, B0, B1, B2> =
    <EqA1<A0, A1, B0, B1> as BitAnd<<A2 as IsEqual<B2>>::Output>>::Output;

/// Compares two three-counter tuples element by element.
///
/// The corresponding counter pairs are compared:
///
/// ```text
/// (A0, A1, A2)
/// (B0, B1, B2)
/// ```
///
/// Their equality results are combined with `BitAnd`:
///
/// ```text
/// A0 == B0
/// A1 == B1
/// A2 == B2
///
/// (A0 == B0) AND (A1 == B1) AND (A2 == B2)
/// ```
///
/// The resulting `Output` is [`B1`] only when all three counter positions
/// are equal. If any corresponding counter differs, the result is [`B0`].
impl<A0, A1, A2, B0, B1, B2> CountersEqual<(B0, B1, B2)> for (A0, A1, A2)
where
    A0: IsEqual<B0>,
    A1: IsEqual<B1>,
    A2: IsEqual<B2>,
    <A0 as IsEqual<B0>>::Output: BitAnd<<A1 as IsEqual<B1>>::Output>,
    EqA1<A0, A1, B0, B1>: BitAnd<<A2 as IsEqual<B2>>::Output>,
    EqA2<A0, A1, A2, B0, B1, B2>: BoolTypeNum,
    (B0, B1, B2): Marker,
{
    type Output = EqA2<A0, A1, A2, B0, B1, B2>;
}

/// Equality result for the first four counter dimensions.
///
/// `EqA3` combines the equality results of the first four corresponding
/// counters into a single type-level boolean.
type EqA3<A0, A1, A2, A3, B0, B1, B2, B3> =
    <EqA2<A0, A1, A2, B0, B1, B2> as BitAnd<<A3 as IsEqual<B3>>::Output>>::Output;

/// Compares two four-counter tuples element by element.
///
/// The corresponding counter pairs are compared:
///
/// ```text
/// (A0, A1, A2, A3)
/// (B0, B1, B2, B3)
/// ```
///
/// Their equality results are combined with `BitAnd`:
///
/// ```text
/// A0 == B0
/// A1 == B1
/// A2 == B2
/// A3 == B3
///
/// (A0 == B0) AND (A1 == B1) AND (A2 == B2) AND (A3 == B3)
/// ```
///
/// The resulting `Output` is [`B1`] only when all four counter positions
/// are equal. If any corresponding counter differs, the result is [`B0`].
impl<A0, A1, A2, A3, B0, B1, B2, B3> CountersEqual<(B0, B1, B2, B3)> for (A0, A1, A2, A3)
where
    A0: IsEqual<B0>,
    A1: IsEqual<B1>,
    A2: IsEqual<B2>,
    A3: IsEqual<B3>,
    <A0 as IsEqual<B0>>::Output: BitAnd<<A1 as IsEqual<B1>>::Output>,
    EqA1<A0, A1, B0, B1>: BitAnd<<A2 as IsEqual<B2>>::Output>,
    EqA2<A0, A1, A2, B0, B1, B2>: BitAnd<<A3 as IsEqual<B3>>::Output>,
    EqA3<A0, A1, A2, A3, B0, B1, B2, B3>: BoolTypeNum,
    (B0, B1, B2, B3): Marker,
{
    type Output = EqA3<A0, A1, A2, A3, B0, B1, B2, B3>;
}
